In [1]:
from pathlib import Path
import json

from tqdm.auto import tqdm

from pydantic import BaseModel, Field
from typing import Literal
import os
import logging
from dotenv import load_dotenv

load_dotenv()
logging.basicConfig(level=logging.INFO)

In [2]:
class PrinciplesMetadata(BaseModel):

    topic: list[
        Literal[
            "program_design",
            "periodization",
            "progressive_overload",
            "volume",
            "frequency",
            "intensity",
            "load",
            "exercise_selection",
            "recovery",
            "fatigue",
            "warmup",
            "energy_systems",
        ]
    ] = Field(min_length=1)

    planner_stage: list[
        Literal[
            "goal_selection",
            "program_design",
            "exercise_selection",
            "progression",
            "recovery",
        ]
    ] = Field(min_length=1)

    goals: list[
        Literal[
            "hypertrophy",
            "strength",
            "fat_loss",
            "endurance",
        ]
    ] = Field(min_length=1)

    applies_to: list[
        Literal[
            "all",
            "hypertrophy",
            "strength",
            "fat_loss",
            #"endurance",
        ]
    ] = Field(min_length=1)

    knowledge_type: list[
        Literal[
            "definition",
            "principle",
            "recommendation",
            "warning",
            "protocol",
        ]
    ] = Field(min_length=1)

class GoalNamespaceMetadata(BaseModel):

    muscle: list[
        Literal[
            "all",
            "chest",
            "back",
            "shoulders",
            "biceps",
            "triceps",
            "forearms",
            "quads",
            "hamstrings",
            "glutes",
            "calves",
            "abs",
        ]
    ] = Field(min_length=1)

    topic: list[
        Literal[
            # Science
            "muscle_physiology",
            "neuromuscular_system",
            "muscle_activation",
            "biomechanics",

            # Goal-specific
            "muscle_growth_mechanisms",
            "hypertrophy_programming",
            "maximal_strength",
            "force_production",
            "power_development",
            "neural_adaptation",

            # Programming
            "volume",
            "frequency",
            "intensity",
            "load",
            "exercise_selection",
            "exercise_order",
            "periodization",
            "recovery",
            "fatigue_management",
            "advanced_techniques",
        ]
    ] = Field(min_length=1)

    experience_level: Literal[
        "all",
        "beginner",
        "intermediate",
        "advanced",
    ] = Field(min_length=1)

    goals: list[
        Literal[
            "hypertrophy",
            "strength",
            "fat_loss",
        ]
    ] = Field(min_length=1)


class CollectionRoute(BaseModel):
    collection: Literal[
        "principles",
        "hypertrophy",
        "strength"
    ]

class Chunk(BaseModel):
    id: str
    
    text: str

    book: str
    chapter: str
    collection: Literal[
    "principles",
    "hypertrophy",
    "strength",
]

    chunk_index: int

    metadata: PrinciplesMetadata | GoalNamespaceMetadata | None = None

In [3]:
from dataclasses import dataclass

@dataclass
class ChapterInfo:
    title: str
    start_page: int
    end_page: int


@dataclass
class BookInfo:
    title: str
    author: str
    slug: str

@dataclass
class BookPaths:
    book_dir: Path
    chapters_dir: Path
    markdown_dir: Path
    chunks_dir: Path

import re

def slugify(text: str) -> str:
    text = text.lower().strip()

    text = re.sub(r"[^\w\s-]", "", text)

    text = re.sub(r"[-\s]+", "_", text)

    return text

import fitz
book_path = "books/Science-and-development-of-muscle-hypertrophy-by-Brad-Schoenfeld-z-lib.org_.pdf"


def extract_book_info(pdf_path: str) -> BookInfo:
    doc = fitz.open(pdf_path)

    metadata = doc.metadata

    title = metadata.get("title", "").strip()
    author = metadata.get("author", "").strip().rstrip(";")

    doc.close()
    return BookInfo(
        title=title,
        author=author,
        slug=slugify(title),
    )

book = extract_book_info(book_path)

print(book)

def create_book_folders(
    root_dir: Path,
    book: BookInfo,
) -> dict[str, Path]:
    """
    Create the folder structure for a book.

    Structure:
    data/
    └── books/
        └── <book_slug>/
            ├── chapters/
            └── markdown/
    """

    book_dir = root_dir / book.slug

    chapters_dir = book_dir / "chapters"
    markdown_dir = book_dir / "markdown"
    chunks_dir = book_dir / "chunks"


    chapters_dir.mkdir(parents=True, exist_ok=True)
    markdown_dir.mkdir(parents=True, exist_ok=True)
    chunks_dir.mkdir(parents=True, exist_ok=True)

    return BookPaths(
        book_dir=book_dir,
        chapters_dir=chapters_dir,
        markdown_dir=markdown_dir,
        chunks_dir=chunks_dir,
    )

paths = create_book_folders(
    root_dir=Path("data/books"),
    book=book,
)
print(paths.chapters_dir)
print(paths.markdown_dir)
print(paths.chunks_dir)

BookInfo(title='Science and Development of Muscle Hypertrophy', author='Brad Schoenfeld', slug='science_and_development_of_muscle_hypertrophy')
data/books/science_and_development_of_muscle_hypertrophy/chapters
data/books/science_and_development_of_muscle_hypertrophy/markdown
data/books/science_and_development_of_muscle_hypertrophy/chunks

In [4]:
def load_chunk(chunk_path: Path) -> Chunk:
    with open(chunk_path, "r", encoding="utf-8") as f:
        return Chunk.model_validate_json(f.read())
    

def load_all_chunks(
    chunks_dir: Path,
) -> list[Chunk]:

    chunk_paths = sorted(
        chunks_dir.glob("*.json")
    )

    return [
        load_chunk(path)
        for path in tqdm(chunk_paths)
    ]

all_chunks = load_all_chunks(
    paths.chunks_dir,
)

print(len(all_chunks))

  0%|          | 0/1221 [00:00<?, ?it/s]

1221

In [5]:
from pathlib import Path

from sentence_transformers import SentenceTransformer, CrossEncoder


MODELS_DIR = Path("assets/models")
MODELS_DIR.mkdir(parents=True, exist_ok=True)


MODELS = {
    "bge-m3": (
        SentenceTransformer,
        "BAAI/bge-m3",
    ),
    "bge-reranker-v2-m3": (
        CrossEncoder,
        "BAAI/bge-reranker-v2-m3",
    ),
}


for model_name, (model_class, huggingface_name) in MODELS.items():

    model_path = MODELS_DIR / model_name

    if model_path.exists():
        print(f"{model_name} already exists.")
        continue

    print(f"⬇️ Downloading {huggingface_name}...")

    model = model_class(
        huggingface_name,
        device="cpu",
    )

    model.save(
        str(model_path),
    )

    print(f"Saved to {model_path}")

WARNING:torchao:Skipping import of cpp extensions due to incompatible torch version. Please upgrade to torch >= 2.11.0 (found 2.10.0+cu128).

bge-m3 already exists.
bge-reranker-v2-m3 already exists.

In [6]:
import gc
gc.collect()

import torch
torch.cuda.empty_cache()

In [ ]:
dense_model = SentenceTransformer(
    "assets/models/bge-m3"
)

reranker = CrossEncoder(
    "assets/models/bge-reranker-v2-m3"
)

In [7]:
from collections import defaultdict

chunks_by_collection = defaultdict(list)

for chunk in all_chunks:
    chunks_by_collection[chunk.collection].append(chunk)

for collection, chunks in chunks_by_collection.items():
    print(collection, len(chunks))

hypertrophy 1221

In [8]:
corpus_by_collection = {
    collection: [
        chunk.text
        for chunk in chunks
    ]
    for collection, chunks in chunks_by_collection.items()
}

In [9]:
BM25_DIR = Path("data/indices/bm25")
BM25_DIR.mkdir(
    parents=True,
    exist_ok=True,
)

In [7]:
from fastembed import SparseTextEmbedding

FASTEMBED_DIR = Path("assets/models/fastembed")
FASTEMBED_DIR.mkdir(
    parents=True,
    exist_ok=True,
)

bm25 = SparseTextEmbedding(
    model_name="Qdrant/bm25",
    cache_dir=str(FASTEMBED_DIR),
)

In [11]:
import fastembed
print(fastembed.__version__)

0.8.0

In [8]:
from qdrant_client import QdrantClient

qdrant = QdrantClient(
    path="data/qdrant",
)

COLLECTIONS = [
    "principles",
    "hypertrophy",
    "strength",
]

In [9]:
from qdrant_client.models import (
    VectorParams,
    SparseVectorParams,
    Distance,
)


def create_collections(
    client: QdrantClient,
    collections: list[str],
) -> None:

    existing = {
        c.name
        for c in client.get_collections().collections
    }

    for collection in collections:

        if collection in existing:
            print(f"{collection} already exists.")
            continue

        client.create_collection(
            collection_name=collection,

            vectors_config={
                "dense": VectorParams(
                    size=1024,
                    distance=Distance.COSINE,
                ),
            },

            sparse_vectors_config={
                "sparse": SparseVectorParams(),
            },
        )

        print(f"Created {collection}")

In [14]:
create_collections(
    client=qdrant,
    collections=COLLECTIONS,
)

principles already exists.
hypertrophy already exists.
strength already exists.

In [10]:
from itertools import islice
from collections.abc import Iterator


def batch_iterator(
    items: list,
    batch_size: int,
) -> Iterator[list]:

    iterator = iter(items)

    while batch := list(islice(iterator, batch_size)):
        yield batch

In [9]:
from sentence_transformers import SentenceTransformer
import numpy as np

def get_chunk_texts(
    chunks: list[Chunk],
) -> list[str]:

    return [
        chunk.text
        for chunk in chunks
    ]

def embed_dense_batch(
    chunks: list[Chunk],
    model: SentenceTransformer,
) -> np.ndarray:

    return model.encode(
        get_chunk_texts(chunks),
        normalize_embeddings=True,
        convert_to_numpy=True,
        show_progress_bar=False,
    )

In [40]:
dense_model = SentenceTransformer(
    "assets/models/bge-m3"
)

INFO:sentence_transformers.base.model:No device provided, using cuda:0
INFO:sentence_transformers.base.model:Loading SentenceTransformer model from assets/models/bge-m3.
The tokenizer you are loading from 'assets/models/bge-m3' with an incorrect regex pattern: https://huggingface.co/mistralai/Mistral-Small-3.1-24B-Instruct-2503/discussions/84#69121093e8b480e709447d5e. This will lead to incorrect tokenization. You should set the `fix_mistral_regex=True` flag when loading this tokenizer to fix this issue.

In [18]:
first_batch = next(
    batch_iterator(
        all_chunks,
        batch_size=64,
    )
)

dense_vectors = embed_dense_batch(
    first_batch,
    dense_model,
)

print(dense_vectors.shape)

(64, 1024)

In [13]:
def embed_sparse_batch(
    chunks: list[Chunk],
    model: SparseTextEmbedding,
):
    return list(
        model.embed(
            get_chunk_texts(chunks),
        )
    )

In [20]:
sparse_vectors = embed_sparse_batch(
    first_batch,
    bm25,
)

print(len(sparse_vectors))
print(type(sparse_vectors[0]))

64
<class 'fastembed.sparse.sparse_embedding_base.SparseEmbedding'>

In [21]:
first_sparse = sparse_vectors[0]

print(first_sparse.indices[:10])
print(first_sparse.values[:10])

[ 920019564 1810453357   97321696 1338150097 1050980247  540174517
 2028158887 1425104078  691807284   65094886]
[1.77469671 1.48719303 1.77469671 1.77469671 1.77469671 1.89693499
 1.77469671 1.77469671 1.48719303 1.48719303]

In [ ]:
del dense_model
import gc
gc.collect()

import torch
torch.cuda.empty_cache()

In [11]:
from qdrant_client.models import (
    PointStruct,
    SparseVector,
)
import uuid

In [12]:
from qdrant_client.models import (
    PointStruct,
    SparseVector,
)
import uuid


def build_points(
    chunks: list[Chunk],
    dense_vectors,
    sparse_vectors,
) -> list[PointStruct]:

    points = []

    for chunk, dense, sparse in zip(
        chunks,
        dense_vectors,
        sparse_vectors,
    ):
        point_id = str(
            uuid.uuid5(
                uuid.NAMESPACE_DNS,
                chunk.id,
            )
        )
        point = PointStruct(
            id=point_id,
            vector={
                "dense": dense.tolist(),
                "sparse": SparseVector(
                    indices=sparse.indices.tolist(),
                    values=sparse.values.tolist(),
                ),
            },
            payload = chunk.model_dump(
                exclude={
                    "collection",
                },
            ),
        )

        points.append(point)

    return points

In [25]:
points = build_points(
    chunks=first_batch,
    dense_vectors=dense_vectors,
    sparse_vectors=sparse_vectors,
)

print(len(points))
print(points[0])

64

In [13]:
from qdrant_client import QdrantClient
from qdrant_client.models import PointStruct


def upsert_batch(
    client: QdrantClient,
    collection_name: str,
    points: list[PointStruct],
) -> None:

    client.upsert(
        collection_name=collection_name,
        points=points,
        wait=True,
    )

In [14]:
from collections import defaultdict
from tqdm import tqdm

def ingest_chunks(
    chunks: list[Chunk],
    client: QdrantClient,
    dense_model: SentenceTransformer,
    sparse_model: SparseTextEmbedding,
    batch_size: int = 64,
) -> None:

    total_batches = (len(chunks) + batch_size - 1) // batch_size

    for batch in tqdm(
        batch_iterator(chunks, batch_size),
        total=total_batches,
        desc="Ingesting Chunks",
    ):
        
        dense_vectors = embed_dense_batch(
            chunks=batch,
            model=dense_model,
        )

        sparse_vectors = embed_sparse_batch(
            chunks=batch,
            model=sparse_model,
        )

        grouped = defaultdict(list)

        for chunk, dense, sparse in zip(
            batch,
            dense_vectors,
            sparse_vectors,
        ):
            grouped[chunk.collection].append(
                (
                    chunk,
                    dense,
                    sparse,
                )
            )

        for collection_name, items in grouped.items():

            group_chunks = [item[0] for item in items]
            group_dense = [item[1] for item in items]
            group_sparse = [item[2] for item in items]

            points = build_points(
                chunks=group_chunks,
                dense_vectors=group_dense,
                sparse_vectors=group_sparse,
            )

            upsert_batch(
                client=client,
                collection_name=collection_name,
                points=points,
            )

In [31]:
ingest_chunks(
    chunks=all_chunks,
    client=qdrant,
    dense_model=dense_model,
    sparse_model=bm25,
    batch_size=64,
)

Ingesting Chunks: 100%|██████████| 20/20 [00:53<00:00,  2.66s/it]

In [32]:
for collection in COLLECTIONS:

    count = qdrant.count(
        collection_name=collection,
        exact=True,
    )

    print(
        f"{collection}: {count.count}"
    )

principles: 0
hypertrophy: 1221
strength: 0

In [33]:
result = qdrant.scroll(
    collection_name="hypertrophy",
    limit=1,
    with_payload=True,
    with_vectors=True,
)

result

([Record(id='002caa39-6ef6-53a3-be97-ce11f65b2f6c', payload={'id': 'science_and_development_of_muscle_hypertrophy_000621', 'text': 'Current evidence suggests little difference in muscle hypertrophy when training with isotonic repetition durations ranging from 0.5 to 6 seconds to muscular failure. Thus, it would seem that a fairly wide range of repetition durations can be used if the primary goal is to maximize muscle growth. Research is limited on the topic, making it difficult to draw concrete conclusions. Concentric tempos of 1 to 3 seconds can be considered viable options; an eccentric tempo of at least 2 seconds appears necessary to ensure loads are lowered under muscular control. On the other hand, training at very slow volitional durations (&gt;10 seconds per repetition) appears to produce inferior increases in muscle growth, although a lack of controlled studies on the topic makes it difficult to draw', 'book': 'Science and Development of Muscle Hypertrophy', 'chapter': 'Chapter 4: Role of Resistance Training Variables in Hypertrophy', 'chunk_index': 169, 'metadata': {'muscle': ['all'], 'topic': ['hypertrophy_programming', 'volume'], 'experience_level': 'all', 'goals': ['hypertrophy']}}, vector={'dense': [-0.012370933244236106, 0.0013809709911718285, -0.041180783966626826, 0.007630304103823396, -0.04508770062483559, -0.033560077141520296, 0.017662932333360068, 0.019544261594821158, -0.011526586921334512, -0.016943733407339408, -0.05245411169457251, -0.01848413156599198, -0.022688074920093133, 0.00924299151759517, 0.008935225741558746, -0.022834611070298827, 0.006136314212720652, -0.020316840203222802, 0.02313358795557823, 0.007737489548644855, 0.0544379516273937, -0.006599224353148119, 0.0474495047697227, 0.004383018516674566, -0.0004749962913060005, 0.038246056275615115, -0.04002433469864616, 0.059174106694351206, 0.05719092241259423, 0.04853624268335935, -0.031969363351624876, 0.0552326230689561, 0.06227386473845649, -0.03265586354346317, -0.0055231295934344594, -0.010945016045478123, 0.0019468859859792028, -0.06158547582451846, -0.010792303364224369, 0.05186503156512135, 0.012296932218298697, -0.023037507134995548, 0.015135477574571477, -0.008455070301762015, 0.024631329679510757, -0.016580612613826557, -0.011745603247778957, -0.03683639531169488, -0.0005282278060925335, -0.03302997208023673, 0.0018195002718021827, -0.0018793017723037272, -0.0013237246904586944, 0.011863751755813966, 0.016096464594324903, 0.0426890161075867, 0.03175345671112275, -0.023959525757265107, -0.0413569156843303, -0.024816849128360866, 0.021671871649920904, 0.015129834691335619, -0.020115009571505423, 0.039609490114218465, -0.007744779010121511, 0.010389987861851796, 0.0069064867493547075, -0.011350709454682924, -0.009723701094299863, -0.06364976339786009, -0.01137300438483364, 0.04156428023454702, -0.008295642785035322, -0.0038329798935262224, -0.058277339951279046, 0.0057370106074242895, -0.018439569645366576, 0.0006753928318395711, 0.058082827652036886, -0.006216577451379287, 0.009486039690716968, 0.0024161666053725177, 0.0036326263393483796, 0.008849924047989071, -0.010065174226823397, 0.017904280842856606, -0.0056349525588159045, -0.021933407506672838, -0.022902474680734617, 0.002436255698100536, 0.010828067080867407, -0.02613181321698452, -0.044924156662506896, -0.035735456592053884, 0.028501080980662223, 0.009952750558407272, -0.02007969568364649, 0.009022689966053269, 0.021752110674193643, 0.013695530001832937, 0.04164958192811669, -0.01615893584728659, 0.009637312547332558, -0.020237005372929988, 0.031127892952709475, -0.007068053979604156, 0.038051283206063324, 0.012078021131300637, -0.00915572287083287, 0.007332573328095003, 0.021816999640454603, 0.009423096257230347, 0.007830362428757839, 0.0014608501757003452, -0.01127812124503018, 0.01446347434930347, -0.006707660098471993, -0.02315718021801935, 0.03524716791256434, -0.021356907682016195, 0.011775441890458219, 0.03693834532688927, 0.1067234380638899, -0.0223533725023946, -0.01569574258480867, -0.002075062043741968, 0.012865240129942864, 0.00707872088225177, -0.003265014941405343, 0.038724208440640374, 0.016303477104623623, 0.050538388691916465, -0.04318933747422054, -0.025642235587107386, -0.00243767480081231, -0.027528288516462895, 0.017502549279713092, 0.06525740490614056, -0.01334939094341212, -0.04271995464217907, 0.022876909877165664, -0.043347263699021796, 0.03759878711421539, -0.02441084838271972, 0.0222959490175693, 0.0152367160593496, -0.005310995274857875, 0.044665550746448145, 0.016635556918065317, -0.0036407965991119328, -0.004997994534855654, 0.03409535290551479, 0.04524431554750843, -0.014066689040140093, 0.011968756508921156, -0.0008119775097270344, 0.02033281238468756, 0.014197546375479361, -0.007176656897322954, 0.026529420883945765, -0.005700211260123013, 0.009762120011488441, -0.033981739006899714, 0.024642080866847733, 0.005458219206755212, 0.006550652157689642, -0.02638275062329512, 0.012564910964343527, -0.02123933752527504, -0.02814195742346697, -0.0105778281664576, 0.0006859397685032244, 0.015535668730243112, 0.042344605583789705, 0.03198956932533096, 0.019991635412729962, 0.06501276510280748, 0.01569444804648587, 0.03271607540795643, -0.036735503278899545, 0.01339874917508962, -0.007412379287389253, 0.01152300598618979, 0.0005383529118557673, -0.052308203255755, -0.011306275125244732, -0.03329621484107746, -0.03369360644121073, 0.0014816211129388527, 0.026309449951903572, -0.001317779127399161, 0.020834519559252564, 0.0376176668846325, 0.0056355863238005555, 0.03874410521526504, -0.0414537471508757, 0.017794813192164628, -0.021340950401711987, -0.006248156270214052, -0.033004126017262395, 0.002523221199377895, -0.005558061173393021, -0.024914976995874135, -0.02802413953493167, -0.030615989659037987, 0.010031536719526368, -0.04888169256310472, -0.014675213321464207, 0.015181264184329598, -0.015151766405697924, -0.028523317237493274, -0.03439841643407509, 0.00878081060271213, 0.0025655016126246793, 0.04106160448454625, 0.014251142124688327, 0.025415188466448912, -0.0041682802202918316, 0.008673672189678659, -0.039683783575431675, -0.024392601911625986, 0.08349638816669569, -0.01701069736020698, -0.06380281321787129, 0.009445737639363856, -0.0033672692662378508, 0.03969855062553693, 0.025021499804712376, 0.030981790798804806, -0.06027006097578816, 0.018494471108768756, -0.008648837542976665, 0.013302004321539919, 0.0017527778807169667, 0.0039400843132871895, -0.0032908617028715825, 0.01511173723184739, 0.01958335292687956, 0.02065464019967071, 0.013684902680393036, -0.007597176961275212, 0.011121685136283943, 0.010034855021716391, -0.010636130819755363, -0.01948221688758022, -0.013908538366608046, -0.009916608724815272, -0.019622312011138086, -0.0084471400903817, 0.01021401353765663, 0.009249310540990993, -0.008178164829225074, -0.06165452780250813, 0.008711082484562493, 0.01141304939116726, 0.0002969195938009415, 0.02728144147872333, -0.01337450312422936, -0.03892664070671498, -0.044628066877084094, -0.0030833940086841824, 0.03012417685507832, -0.01131560883968437, 0.016847213002520494, -0.02084428726999323, -0.005761950959233935, 0.03304078659750605, -0.030020326941913773, -0.03899208660385149, 0.0525170839990577, 0.011987999495126682, -0.05028726688374406, 0.01731820329725631, 0.04532865984151275, -0.029281709941051122, 0.03499752876986668, -0.045076591809645405, 0.01639620330143744, 0.02257688432271254, -0.02186654786192912, -0.025486538948453454, 0.015044747201948854, 0.021993747893675843, -0.005839816042366521, 0.02074369139776383, -0.059861057646296144, -0.04130070478144478, -0.00011127376884849026, -0.0034251865848370115, 0.027436752549848023, 0.006879079789812734, -0.036524137767075096, 0.07381456771544473, -0.05147252382035842, -0.03879368137641559, -0.01689525434413437, 0.025375674313959894, -0.15282913382345387, -0.003773847431850319, -0.015055087676048165, -0.0056225277848846325, -0.0018485517141092515, -0.000985551117259181, -0.03417295442437014, 0.008376313011641484, -0.013275122627907341, 0.040187949441487465, 0.01416423110577923, -0.05312480920564731, 0.018609778151751345, 0.03600809567606079, 0.005667712294624273, 0.02289837499893824, 0.000907174272393949, -0.038825864157913906, -0.014236747603596825, -0.03033451604946987, 0.013711132448251541, -0.016135079089245705, 0.033644752986346865, -0.0050685552553510335, -0.06579307927617976, 0.031472882759122855, 0.02007512102735758, -0.00136771012243531, -0.05046243747659205, -0.03450445681784052, -0.054077950764371045, -0.007534565078610834, 0.006921597923136421, 0.010688939601422772, 0.015595363710729785, 0.03148566050429466, 0.0009230078614240563, 0.01766636332557675, 0.005085945841035663, 0.014149426802772596, 0.031607108688069006, 0.03808374538432196, 0.008495380735017934, 0.03225066373520159, 0.024132707045179645, -0.020370434089786702, -0.028936075659443942, 5.981986137979088e-05, 0.02256821929785259, -0.05189421921334907, 0.04011820083424207, -0.010996780814584483, -0.010712829887074896, 0.006368776042594059, -0.032936973937242875, -0.008236538263035451, 0.05609962474382922, 0.06886524409623619, -0.03401444332901729, 0.006186616805448022, -0.002439155370811353, -0.02578567602120877, 0.011533676148466274, -0.013002497513738448, 0.004808915571279114, -0.0009752419588800888, 0.022700044277305088, -0.01143462347767636, -0.04219553437364541, -0.029057982053905206, 0.046750752098622, -0.01625349861213822, 0.037908004822082925, -0.017362090940366816, 0.03300221866871197, 0.028414412105612068, -0.02867301615902575, -0.021627212871751927, 0.028450914361024874, -0.0943092812095103, 0.00979609931415559, -0.005984502586018918, -0.01917456007628032, -0.01405192944061511, -0.02433678588949504, 0.0031731516149196373, 0.037255985915757815, 0.0008111978763504348, 0.012916350179307548, 0.22862534727582878, -0.04087998541447016, 0.021790006188117897, -0.005031713532874442, -0.019528037956272115, -0.014135902136928212, 0.004145655601963942, -0.005786238919608243, -0.022734216363736858, -0.015143830606382403, -0.009178114658527161, 0.02327353779282073, -0.033091227025968506, 0.032927809723504495, -0.027151389737376304, 0.009924051854510103, -0.06390829853340622, 0.003348469356728059, 0.0417258497931028, -0.018689376426120428, 0.016178244026069523, -0.030295717152687265, 0.009344760856217896, -0.007007413241083811, -0.043154122306550254, 0.003911405167163242, -0.02523212770908959, 0.05298105770981944, 0.024787428649499545, -0.019489272587100745, -0.03914600814175488, 0.02373775364744141, 0.020881670556523565, -0.01386976089024373, -0.028757384667415967, 0.006628222477240094, -0.001020859650013536, 0.006234098422218731, -0.009669744923270088, 0.037302920846200835, 0.0011129232108441356, -0.0025103314626713303, -0.01603202638817059, -0.0014653752390643034, 0.012587877378041538, -0.02853556040353034, -0.024999989979458147, -0.030838033715041728, -0.006049973628863867, 0.004106594072226636, 0.03204303841467525, 0.05736471837338146, 0.030614048782876324, -0.004297222756500399, 0.013508008209533894, 0.02322037231462265, -0.028545616824256662, 0.022775526106072176, -0.011458425287687717, -0.013563177893825976, -0.010191097415375477, 0.0047537151533433965, -0.018894792649595205, 0.03750115098500027, -0.06637212347400036, -0.004092264743712541, -0.022912797459705776, 0.016288084205775256, 0.019290817068247985, 0.012721994342251165, 0.04995179333098706, 0.03281801424728041, -0.0036325141149829857, -0.0012905151258662164, 0.03721719819484562, -0.02160376775827124, -0.0038797173835919546, 0.02873126293297145, -0.004838662013027469, -0.002913845111484394, -0.05386973684800297, -0.04468288452145818, -0.05772169057552228, -0.05655477696754523, 0.034447873385941234, -0.03856392410718205, -0.019338424413560838, 0.023331164305958527, -0.02509415413826506, 0.0012409042729512633, -0.030158173852873622, 0.058190373053017885, -0.014519979550109864, -0.024127543793048996, -0.03924666175598141, 0.023133282481786952, 0.01243458448284886, -0.03241095924453034, -0.024821887583271907, 0.00020456479095154134, 0.007701602897427278, 0.03344855685596253, 0.0021943618992601136, -0.01951496032524424, 0.0172288056471804, -0.003251899358984189, -0.06575726433679734, 0.0008988013335638497, -0.054725164046418716, 0.010047561055053049, -0.04721898009072082, 0.006186085020280886, -0.012052254230741721, -0.04217498939853681, 0.013772467487721273, 0.054839049891213826, -0.00743341134418334, 0.03284402794831094, -0.009711138484633501, 0.03733288708006731, -0.012181294555816399, 0.009660813540165307, -0.07807590475205008, 0.02939920000405432, -0.01290109884148441, 0.022948312513232132, -0.003964174833284206, 0.018833466923350816, -0.010819600427707285, -0.024480803743567744, 0.02872800330410109, -0.02752407521331732, -0.008186760936217476, -0.033394242125757014, 0.066525970506101, -0.013379491287723543, 0.026330691556267893, -0.009615201087721115, -0.0088954806210812, 0.0460115949306894, -0.03933717885574366, -0.041222652502482776, -0.0094577256230265, 0.01880560734105713, 0.025525330394655786, 0.00631473931216506, -0.03895574267326953, 0.007473150411064413, 0.005258114315694051, -0.01830623592340837, -0.004038851533720315, 0.03436940014919369, -0.025936676931644323, -0.04706395959222685, 0.029130010538714782, -0.10813473443018053, -0.02330309610741714, 0.015599597502971114, 0.012296753404372094, -0.028706776600897318, 0.0014677402162250653, -0.009134293139316598, -0.03945709221998133, 0.008036955843916081, -0.00010549110719694426, 0.009446913899724789, 0.002106896044951155, 0.031472353767923324, -0.047492271100501804, -0.006296303782596847, -0.009558508691085309, -0.013931550415110242, -0.005818818910167474, 0.03583586433713133, -0.009219375040768158, -0.02282003587263565, -0.04825755745345919, 0.027518800202482548, -0.03689770241148858, 0.028824037558557055, -0.0065154323334066875, 0.00509423414593045, 0.00885423048338808, 0.04308822192401695, -0.0054857123136316166, 0.04402576196764463, -0.014673180244371637, -0.008927805894927275, 0.05369516602686713, -0.0380031971609678, 0.003508842398657789, 0.0842370056483622, -0.05782771605812716, -0.0007348002664937527, 0.04873041225590885, 0.025726877904322716, 0.026383059822376535, 0.00529397908083207, 0.019348538576284293, -0.041166765699839215, 0.012346683468085708, 0.029238209728114924, -0.0215556407349842, 0.05878480269910657, 0.001995653293508634, -0.022538687060287145, -0.014388972271842559, 0.017671575006479187, 0.0018920685744357529, -0.006923731583062705, -0.014745064374188382, -0.03317950895164822, -0.01707418375473115, 0.03465096130308004, -0.016685013869931462, -0.052029585081077315, 0.025630702088841526, 0.0030478021210487397, 0.005519451335084894, 0.008354074892165365, -0.016576274513461376, 0.020057155815669234, 0.01999078418393353, -0.017744771369746885, -0.013368421588079805, 0.030060928879122956, -0.00382255001246361, -0.058484399027704484, -0.020010442539989393, -0.017440782106587404, -0.003473327345131433, -0.028119143746664597, 0.031759156405033205, 0.021618477066379364, -0.017278275637562027, -0.042677314971264646, 0.0037818786917256145, 0.01636871252286737, -0.018879612092284677, -0.0108557264288162, -0.014066902313000467, 0.02701258728949617, -0.004211422339713559, 0.018921396809112534, -0.04312731884401057, -0.015955417659136897, -0.026791949530519357, 0.038100442134718464, 0.02660279047320486, 0.034219438594706525, -0.0019790319802374095, 0.009340764551222836, -0.004353184996269245, 0.017601019873919016, 0.0019320422181801748, 0.024940009082953418, -0.04253217021692533, 0.005790146748962536, -0.02378963948847724, -0.009468261674858033, -0.012708199592871809, -0.03344199289474016, 0.042547730753829886, 0.02967643050815576, -0.09292546258327428, -0.04514292432583466, -0.022180701579228912, 0.008294877237912055, -0.014512137814370316, -0.05338147797083453, -0.05032281732752673, 0.027881744044713865, -0.0595166322213386, -0.0874460674303934, 0.06195314333464419, 0.03008556422280259, -0.02383808316142597, -0.007726929748088696, 7.340308776650313e-05, -0.08567418533052854, -0.05511614442222525, 0.05295267472426142, 0.03191573780009481, -0.013542217548867037, -6.224651319260531e-05, -0.015122263970453579, 0.05895092083692031, -0.01148303734830399, 0.01680110136119787, -0.05478941785071122, 0.010314195902680758, -0.026693626085273866, -0.05255577113713618, 0.026813165057852716, -0.015362557291518655, 0.026403349615110715, -0.016240337162082247, -0.008341122989679631, -0.02925040260273513, 0.017403413721217616, -0.009381397222075654, -0.011626202110935197, -0.02376584606036869, -0.020673646629952504, -0.026987657647895673, -0.019368683082703106, -0.03283803023118948, 0.009241774279042726, 0.054501814276221756, -0.0021764120543935847, 0.02999226433130759, -0.013046672004189543, -0.0011662304828980751, -0.0022827690878207056, -0.03267893799057517, 0.023211344073974294, 0.04717757349084193, -0.050289055023010086, 0.020187768213181956, -0.01238555314538093, -0.00556881189506873, -0.03248949208592008, -0.036666600312515375, 0.00021522011027513396, -0.08801798142289073, 0.0068149158581447995, -0.04975912877565312, 0.022080945759925533, -0.02205347733309629, -0.02359121004665544, -0.02385968053099843, -0.009390735593127964, -0.04820727721247264, -0.010030378154293588, -0.017507962126282955, -0.04112234906552918, -0.009017524851277553, -0.037810193604231344, 0.03420074881408642, 0.02342030118572481, 0.002673566691579868, -0.03268169097998682, 0.04854836850275708, -0.02608619890189526, -0.013344130833737896, 0.07029594177356319, 0.01659555661521335, -0.041936984336938724, -0.0015360641328234785, 0.027917665154865212, 0.046887973160838745, 0.006632993176922497, -0.013364889081706872, -0.025908955185085725, 0.04495231985594679, -0.05397092317871917, -0.005862435072759205, 0.05977208654194098, 0.07779430261997222, -0.0028868672588001406, -0.01840379754682073, 0.036464749191702235, 0.00828978662893909, -0.024961060697520725, -0.011829861860110117, 0.03151807052849137, 0.005420874570110051, -0.029170008978921684, 0.04510008721454295, 0.02933936253121988, 0.019103129500537823, 0.04482961624939609, -0.0009394733527937458, 0.030063110036498492, -0.01756434439251481, 0.04117368356362465, 0.03430484087110991, 0.011095966664496816, 0.001076981145935763, -0.036750728539691725, -0.020399103922685305, -0.05014927468646885, 0.012902089768660998, -0.05198902412205964, -0.005924237636141199, -0.04609098086352065, -0.02686620387618612, 0.014840157992884614, 0.06207454681493689, -0.015112160983600536, -0.06281017240781908, 0.010439658086578317, -0.04745058137857246, 0.03206376965429073, -0.14378865932228393, -0.01360478379672723, -0.04473054960876816, 0.013332572189763605, -0.02994214241515189, -0.013398854414536006, 0.03659138670463819, -0.004614766022164097, -0.055188344270381155, 0.0022679172873648185, -0.002071866210465215, -0.02276171831817734, 0.03506998193775193, -0.017116305610316455, 0.0018107387386446098, 0.04173159791578505, -0.02745447561767743, -0.03285054348076152, 0.002584613748014125, 0.06657500277489145, -0.01098842405748342, -0.029262349608206263, 0.0622576261987469, -0.03350719292272761, -0.009413887340010318, 0.004565962858717092, 0.0172791361795838, 0.016982165363043467, 0.003821465953033582, -0.03570624659208533, 0.018589523749273473, 0.0027360568038228743, 0.03082331136841812, 0.05051668142628495, 0.04078877541074233, 0.007857141676911634, -0.007664133929223777, 0.02117100080299178, 0.016114452157754075, 0.06518198268201567, 0.012269967636960557, 0.017881236198065704, 0.0107019157182944, 0.0003184362584550309, -0.024779013219078817, 0.08015491467201531, 0.00052257822897596, -0.010392721293490226, -0.023283085711443278, 0.004472362150043485, -0.024731981431092218, 0.04999353893226847, -0.014406821068214106, 0.019043046158554306, -0.035817375722178656, 0.01266896763111071, -0.009098971800877395, -0.026787872200463806, 0.024805202008745808, 0.033686830138450516, -0.007012112228931066, 0.02968098281270385, -0.03438356370229667, 0.00428364733357789, 0.003670602878333123, 0.03036334979513

In [34]:
point = result[0][0]

len(
    point.vector["dense"]
)

1024

In [35]:
point.vector["sparse"]

SparseVector(indices=[19522071, 97321696, 131004638, 150760872, 223131028, 259182696, 264741300, 267423339, 301705055, 327797310, 330588669, 372734888, 407983593, 436751995, 446656910, 487501795, 520409122, 522609393, 551536775, 563445918, 608954612, 614428231, 640124220, 662216322, 670727360, 679262712, 724849589, 763520878, 764297089, 769443847, 825859403, 834323496, 897829118, 917062287, 1010544659, 1052767088, 1053731502, 1078715859, 1079573775, 1117092987, 1120066484, 1187906460, 1190790875, 1364383302, 1394226660, 1408635353, 1434869899, 1441330805, 1445293717, 1480150064, 1495971352, 1543434194, 1559397529, 1612148533, 1623065834, 1660786075, 1670835917, 1717433246, 1732871439, 1807167981, 1810453357, 1903144703, 1951551190, 2031875777], values=[1.3790401567091088, 1.3790401567091088, 1.3790401567091088, 1.3790401567091088, 1.3790401567091088, 1.3790401567091088, 1.3790401567091088, 1.3790401567091088, 1.3790401567091088, 1.3790401567091088, 1.3790401567091088, 1.3790401567091088, 1.3790401567091088, 1.9149948996939816, 1.3790401567091088, 1.3790401567091088, 1.3790401567091088, 1.835723598435463, 1.3790401567091088, 1.3790401567091088, 1.3790401567091088, 1.6953642384105962, 1.3790401567091088, 1.6953642384105962, 1.3790401567091088, 1.3790401567091088, 1.3790401567091088, 1.6953642384105962, 1.3790401567091088, 1.3790401567091088, 1.3790401567091088, 1.3790401567091088, 1.3790401567091088, 1.6953642384105962, 1.3790401567091088, 1.3790401567091088, 1.6953642384105962, 1.3790401567091088, 1.3790401567091088, 1.3790401567091088, 1.6953642384105962, 1.835723598435463, 1.6953642384105962, 1.3790401567091088, 1.3790401567091088, 1.3790401567091088, 1.835723598435463, 1.3790401567091088, 1.3790401567091088, 1.3790401567091088, 1.3790401567091088, 1.3790401567091088, 1.3790401567091088, 1.6953642384105962, 1.6953642384105962, 1.3790401567091088, 1.3790401567091088, 1.3790401567091088, 1.3790401567091088, 1.6953642384105962, 1.3790401567091088, 1.6953642384105962, 1.3790401567091088, 1.3790401567091088])

In [ ]:
point.payload

{'id': 'science_and_development_of_muscle_hypertrophy_000621',
 'text': 'Current evidence suggests little difference in muscle hypertrophy when training with isotonic repetition durations ranging from 0.5 to 6 seconds to muscular failure. Thus, it would seem that a fairly wide range of repetition durations can be used if the primary goal is to maximize muscle growth. Research is limited on the topic, making it difficult to draw concrete conclusions. Concentric tempos of 1 to 3 seconds can be considered viable options; an eccentric tempo of at least 2 seconds appears necessary to ensure loads are lowered under muscular control. On the other hand, training at very slow volitional durations (&gt;10 seconds per repetition) appears to produce inferior increases in muscle growth, although a lack of controlled studies on the topic makes it difficult to draw',
 'book': 'Science and Development of Muscle Hypertrophy',
 'chapter': 'Chapter 4: Role of Resistance Training Variables in Hypertrophy',
 'chunk_index': 169,
 'metadata': {'muscle': ['all'],
  'topic': ['hypertrophy_programming', 'volume'],
  'experience_level': 'all',
  'goals': ['hypertrophy']}}

In [ ]:
from sentence_transformers import SentenceTransformer, CrossEncoder

def embed_dense_query(
    query: str,
    model: SentenceTransformer,
) -> list[float]:

    return model.encode(
        query,
        normalize_embeddings=True,
        convert_to_numpy=True,
    ).tolist()

def embed_sparse_query(
    query: str,
    model: SparseTextEmbedding,
) -> SparseVector:

    sparse = list(
        model.embed([query])
    )[0]

    return SparseVector(
        indices=sparse.indices.tolist(),
        values=sparse.values.tolist(),
    )

query = "How do I build muscle?"

dense_vector = embed_dense_query(
    query,
    dense_model,
)

sparse_vector = embed_sparse_query(
    query,
    bm25,
)

In [78]:
import inspect

print(inspect.signature(qdrant.query_points))

(collection_name: str, query: Union[int, str, uuid.UUID, qdrant_common_pb2.PointId, list[float], list[list[float]], qdrant_client.http.models.models.SparseVector, qdrant_client.http.models.models.NearestQuery, qdrant_client.http.models.models.RecommendQuery, qdrant_client.http.models.models.DiscoverQuery, qdrant_client.http.models.models.ContextQuery, qdrant_client.http.models.models.OrderByQuery, qdrant_client.http.models.models.FusionQuery, qdrant_client.http.models.models.RrfQuery, qdrant_client.http.models.models.FormulaQuery, qdrant_client.http.models.models.SampleQuery, qdrant_client.http.models.models.RelevanceFeedbackQuery, numpy.ndarray[tuple[Any, ...], numpy.dtype[Union[numpy.bool, numpy.int8, numpy.int16, numpy.int32, numpy.int64, numpy.uint8, numpy.uint16, numpy.uint32, numpy.uint64, numpy.float16, numpy.float32, numpy.float64, numpy.longdouble]]], qdrant_client.http.models.models.Document, qdrant_client.http.models.models.Image, qdrant_client.http.models.models.InferenceObject, NoneType] = None, using: str | None = None, prefetch: qdrant_client.http.models.models.Prefetch | list[qdrant_client.http.models.models.Prefetch] | None = None, query_filter: qdrant_client.http.models.models.Filter | qdrant_common_pb2.Filter | None = None, search_params: qdrant_client.http.models.models.SearchParams | points_pb2.SearchParams | None = None, limit: int = 10, offset: int | None = None, with_payload: Union[bool, Sequence[str], qdrant_client.http.models.models.PayloadSelectorInclude, qdrant_client.http.models.models.PayloadSelectorExclude, points_pb2.WithPayloadSelector] = True, with_vectors: Union[bool, Sequence[str]] = False, score_threshold: float | None = None, lookup_from: qdrant_client.http.models.models.LookupLocation | points_pb2.LookupLocation | None = None, consistency: Union[Annotated[int, Strict(strict=True)], qdrant_client.http.models.models.ReadConsistencyType, NoneType] = None, shard_key_selector: Union[Annotated[int, Strict(strict=True)], Annotated[str, Strict(strict=True)], List[Union[Annotated[int, Strict(strict=True)], Annotated[str, Strict(strict=True)]]], qdrant_client.http.models.models.ShardKeyWithFallback, NoneType] = None, timeout: int | None = None, **kwargs: Any) -> qdrant_client.http.models.models.QueryResponse

In [15]:
from qdrant_client.models import (
    Prefetch,
    FusionQuery,
    Fusion,
    Filter,
)

def hybrid_search(
    client: QdrantClient,
    collection_name: str,
    query: str,
    dense_model: SentenceTransformer,
    sparse_model: SparseTextEmbedding,
    top_k: int = 10,
    query_filter: Filter | None = None,
):

    dense_vector = embed_dense_query(
        query=query,
        model=dense_model,
    )

    sparse_vector = embed_sparse_query(
        query=query,
        model=sparse_model,
    )

    return client.query_points(
        collection_name=collection_name,

        prefetch=[
            Prefetch(
                using="dense",
                query=dense_vector,
                limit=top_k,
            ),
            Prefetch(
                using="sparse",
                query=sparse_vector,
                limit=top_k,
            ),
        ],

        query=FusionQuery(
            fusion=Fusion.RRF,
        ),

        query_filter=query_filter,

        limit=top_k,
        with_payload=True,
    )

In [39]:
results = hybrid_search(
    client=qdrant,
    collection_name="hypertrophy",
    query="user is having backpain what is the best exercises for him?",
    dense_model=dense_model,
    sparse_model=bm25,
    top_k=10,
)

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

In [40]:
for point in results.points:

    print(point.score)
    print(point.payload["chapter"])
    print(point.payload["text"][:250])
    print("-" * 80)

0.5
Chapter 8: Program Design for Maximal Hypertrophy
The midback muscles (middle trapezius and rhomboids) are best targeted using sagittal plane exercises (e.g., bent-over row and seated row). A neutral grip reduces biceps brachii activation, which seemingly allows the back musculature to carry out a g
--------------------------------------------------------------------------------
0.5
Chapter 8: Program Design for Maximal Hypertrophy
As noted in a recent review (121), practitioners are best served by viewing set and volume prescription for single- and multi-joint exercises on a 1:1 basis, and then using logical rationale and personal expertise to guide exercise program design. Wh
--------------------------------------------------------------------------------
0.375
Chapter 8: Program Design for Maximal Hypertrophy
activation occurs in the lengthened position, whereas an exercise such as the hip thrust is best for optimizing mechanical tension. Indeed, research shows that the gluteus maximus is optimally developed when performing deep versus shallow squats, cor
--------------------------------------------------------------------------------
0.3333333333333333
Chapter 8: Program Design for Maximal Hypertrophy
Electromyographic research investigating the ability for reverse crunch variations to enhance muscle activation in the lower abdominal region has produced conflicting results; some studies observe a beneficial effect (41, 1 1 1, 146) and others fail
--------------------------------------------------------------------------------
0.3333333333333333
Chapter 8: Program Design for Maximal Hypertrophy
## KEY POINT

Maximal hypertrophy can be best achieved by systematically varying the exercises performed and fully working all aspects of the targeted musculature, varying the angles and planes involved, and using both multijoint and single-joint exe
--------------------------------------------------------------------------------
0.25
Chapter 8: Program Design for Maximal Hypertrophy
The pectorals can benefit from the use of a variety of training angles. The sternal head is best targeted during flat supine exercises ( a ) and decline exercises ( b ) (55), whereas the clavicular head is more aligned with gravitational forces when
--------------------------------------------------------------------------------
0.2
Chapter 8: Program Design for Maximal Hypertrophy
## Back

The back muscles benefit from being trained in all three planes of movement. The frontal and sagittal planes, in particular, should be exploited to optimize muscular development. The latissimus dorsi (lats) are maximally stimulated by humera
--------------------------------------------------------------------------------
0.2
Chapter 8: Program Design for Maximal Hypertrophy
In totality, the findings of increased muscle activation combined with those showing site-specific hypertrophy in the region of activation seem to suggest that an internal attentional focus is the best approach for maximizing muscle development. The
--------------------------------------------------------------------------------
0.16666666666666666
Chapter 5: Advanced Training Practices
Recently, foam rolling has been advocated for counteracting DOMS. Drinkwater and colleagues (14) found that 15 minutes of foam rolling for the lower-body musculature performed immediately after a muscle-damaging eccentric bout and 24, 48, and 72 hour
--------------------------------------------------------------------------------
0.16666666666666666
Chapter 1: Hypertrophy-Related Responses and Adaptations to Exercise Stress
not factor into the relevance of post-exercise systemic responses to muscular adaptations.

Evidence from the body of literature as to whether post-exercise anabolic hormonal elevations are associated with increases in muscle growth remains murky. Al
--------------------------------------------------------------------------------

In [41]:
from collections import defaultdict

chapters: dict[str, list[Chunk]] = defaultdict(list)

for chunk in all_chunks:
    chapters[chunk.chapter].append(chunk)

In [42]:
for chapter in chapters:
    print(chapter)

Chapter 1: Hypertrophy-Related Responses and Adaptations to Exercise Stress
Chapter 2: Mechanisms of Hypertrophy
Chapter 3: The Measurement of Muscle Hypertrophy
Chapter 4: Role of Resistance Training Variables in Hypertrophy
Chapter 5: Advanced Training Practices
Chapter 6: Role of Aerobic Training in Hypertrophy
Chapter 7: Factors in Maximal Hypertrophic Development
Chapter 8: Program Design for Maximal Hypertrophy
Chapter 9: Nutrition for Hypertrophy

In [43]:
from pathlib import Path

chapter_names = list(chapters.keys())
idx = 7

chapter_name = chapter_names[idx]
selected_chapter = chapters[chapter_name]

lines = [f"# {chapter_name}", ""]

for chunk in sorted(selected_chapter, key=lambda c: c.chunk_index):
    lines.extend([
        "---",
        "",
        f"## Chunk {chunk.chunk_index}",
        "",
        f"**ID:** `{chunk.id}`",
        "",
        f"**Book:** {chunk.book}",
        "",
        f"**Collection:** {chunk.collection}",
        "",
        "### Text",
        "",
        chunk.text,
        "",
    ])

Path(f"{chapter_name}.md").write_text(
    "\n".join(lines),
    encoding="utf-8",
)

print(f"Saved to {chapter_name}.md")

Saved to Chapter 8: Program Design for Maximal Hypertrophy.md

In [16]:
from typing import Iterable


def hit_rate(
    ground_truth: set[int],
    retrieved: list[int],
) -> float:
    """
    Computes Hit Rate for a single query.

    Returns:
        1.0 if at least one relevant chunk is retrieved.
        0.0 otherwise.
    """
    return float(bool(ground_truth.intersection(retrieved)))

def negative_success_rate(
    retrieved: list[int],
) -> float:
    """
    Computes Negative Success Rate for a single negative query.

    Returns:
        1.0 if no chunks are retrieved.
        0.0 otherwise.
    """
    return float(len(list(retrieved)) == 0)


def precision_at_k(
    ground_truth: set[int],
    retrieved: list[int],
) -> float:
    """
    Computes Precision@k for a single query.

    Precision@k = (# relevant retrieved) / (# retrieved)
    """
    retrieved = list(retrieved)

    if not retrieved:
        return 0.0

    relevant_retrieved = len(
        ground_truth.intersection(retrieved)
    )

    return relevant_retrieved / len(retrieved)

def recall_at_k(
    ground_truth: set[int],
    retrieved: list[int],
) -> float:
    """
    Computes Recall@k for a single query.

    Recall@k = (# relevant retrieved) / (# relevant)
    """

    if not ground_truth:
        return 0.0

    relevant_retrieved = len(
        ground_truth.intersection(retrieved)
    )

    return relevant_retrieved / len(ground_truth)

def reciprocal_rank(
    ground_truth: set[int],
    retrieved: list[int],
) -> float:
    """
    Computes Reciprocal Rank (RR) for a single query.

    RR = 1 / rank of the first relevant retrieved chunk.
    Returns 0.0 if no relevant chunk is retrieved.
    """

    for rank, chunk_idx in enumerate(retrieved, start=1):
        if chunk_idx in ground_truth:
            return 1.0 / rank

    return 0.0

In [17]:
from math import log2


def ndcg(
    ground_truth: set[int],
    retrieved: list[int],
) -> float:
    """
    Computes Normalized Discounted Cumulative Gain (nDCG)
    for a single query.
    """

    if not ground_truth:
        return 0.0

    # DCG
    dcg = 0.0

    for rank, chunk_idx in enumerate(retrieved, start=1):
        if chunk_idx in ground_truth:
            dcg += 1 / log2(rank + 1)

    # IDCG (ideal ranking)
    ideal_hits = min(len(ground_truth), len(retrieved))

    idcg = sum(
        1 / log2(rank + 1)
        for rank in range(1, ideal_hits + 1)
    )

    if idcg == 0:
        return 0.0

    return dcg / idcg

In [18]:
import json

with open("chapter_8_eval_dataset_v2.json", "r", encoding="utf-8") as f:
    evaluation_dataset = json.load(f)

print(len(evaluation_dataset))

54

In [19]:
from abc import ABC, abstractmethod

class ScoredChunk(Chunk):
    score: float
    
class BaseRetriever(ABC):

    @abstractmethod
    def retrieve(
        self,
        query: str,
        query_filter=None,
    ) -> list[ScoredChunk]:
        """
        Retrieve the most relevant chunk indices
        for a given query.
        """
        pass

In [20]:
import pandas as pd

class RetrieverEvaluator:

    POSITIVE_METRICS = {
        "Precision@k": "precision",
        "Recall@k": "recall",
        "MRR": "reciprocal_rank",
        "nDCG": "ndcg",
        "Hit Rate": "hit_rate",
    }

    NEGATIVE_METRICS = {
        "Negative Success Rate": "negative_success",
    }


    def __init__(
        self,
        retriever: BaseRetriever,
        evaluation_dataset: list[dict],
    ):
        self.retriever = retriever
        self.dataset = evaluation_dataset

        self.results = pd.DataFrame()


    @property
    def positive_results(self) -> pd.DataFrame:
        return self.results[
            self.results["type"] != "negative"
        ]


    @property
    def negative_results(self) -> pd.DataFrame:
        return self.results[
            self.results["type"] == "negative"
        ]

    def _check_results(self) -> None:
        if self.results.empty:
            raise ValueError(
                "Run evaluate() before requesting reports."
            )
        

    def _evaluate_sample(
        self,
        sample: dict,
    ) -> dict:

        question = sample["question"]
        ground_truth = set(sample["relevant_chunks"])
        query_type = sample["type"]

        retrieved_chunks = self.retriever.retrieve(question)

        retrieved_ids = [
            chunk.chunk_index
            for chunk in retrieved_chunks
        ]

        row = {
            "question": question,
            "type": query_type,

            "ground_truth": sorted(ground_truth),

            "retrieved": retrieved_ids,
            "retrieved_chunks": retrieved_chunks,

            "num_ground_truth": len(ground_truth),
            "num_retrieved": len(retrieved_ids),
        }

        if query_type == "negative":

            row["negative_success"] = negative_success_rate(
                retrieved=retrieved_ids,
            )

        else:

            row["hit_rate"] = hit_rate(
                ground_truth=ground_truth,
                retrieved=retrieved_ids,
            )

            row["precision"] = precision_at_k(
                ground_truth=ground_truth,
                retrieved=retrieved_ids,
            )

            row["recall"] = recall_at_k(
                ground_truth=ground_truth,
                retrieved=retrieved_ids,
            )

            row["reciprocal_rank"] = reciprocal_rank(
                ground_truth=ground_truth,
                retrieved=retrieved_ids,
            )

            row["ndcg"] = ndcg(
                ground_truth=ground_truth,
                retrieved=retrieved_ids,
            )

        return row
    

    def evaluate(
        self,
    ) -> pd.DataFrame:

        rows = []

        for sample in self.dataset:
            rows.append(
                self._evaluate_sample(sample)
            )

        self.results = pd.DataFrame(rows)

        return self.results
    

    def summary(
        self,
    ) -> pd.DataFrame:

        self._check_results()

        rows = []

        for display_name, column in self.POSITIVE_METRICS.items():

            rows.append(
                {
                    "Metric": display_name,
                    "Value": self.positive_results[column].mean(),
                }
            )

        for display_name, column in self.NEGATIVE_METRICS.items():

            rows.append(
                {
                    "Metric": display_name,
                    "Value": self.negative_results[column].mean(),
                }
            )

        return pd.DataFrame(rows)
    
    def summary_by_type(
        self,
    ) -> pd.DataFrame:

        self._check_results()

        rows = []

        for query_type, group in self.results.groupby("type"):

            row = {
                "Type": query_type,
                "Count": len(group),
            }

            if query_type == "negative":

                for display_name, column in self.NEGATIVE_METRICS.items():
                    row[display_name] = group[column].mean()

            else:

                for display_name, column in self.POSITIVE_METRICS.items():
                    row[display_name] = group[column].mean()

            rows.append(row)

        return pd.DataFrame(rows)

In [21]:


class HybridRetriever(BaseRetriever):

    def __init__(
        self,
        client: QdrantClient,
        collection_name: str,
        dense_model: SentenceTransformer,
        sparse_model: SparseTextEmbedding,
        top_k: int = 10,
    ):
        self.client = client
        self.collection_name = collection_name
        self.dense_model = dense_model
        self.sparse_model = sparse_model
        self.top_k = top_k

    def retrieve(
        self,
        query: str,
        query_filter: Filter | None = None,
    ) -> list[ScoredChunk]:

        results = hybrid_search(
            client=self.client,
            collection_name=self.collection_name,
            query=query,
            dense_model=self.dense_model,
            sparse_model=self.sparse_model,
            top_k=self.top_k,
            query_filter=query_filter,
        )


        retrieved_chunks = []

        for point in results.points:

            retrieved_chunks.append(
                ScoredChunk(
                    **point.payload,
                    collection=self.collection_name,
                    score=point.score,
                )
            )

        return retrieved_chunks

In [73]:
hybrid_retriever = HybridRetriever(
    client=qdrant,
    collection_name="hypertrophy",
    dense_model=dense_model,
    sparse_model=bm25,
)

In [ ]:
evaluator = RetrieverEvaluator(
    retriever=hybrid_retriever,
    evaluation_dataset=evaluation_dataset,
)

In [ ]:
results = evaluator.evaluate()

In [53]:
results.head()

,question,type,ground_truth,retrieved,retrieved_chunks,num_ground_truth,num_retrieved,hit_rate,precision,recall,reciprocal_rank,ndcg,negative_success
0,Why can a muscle actually get stronger when it...,single_chunk,[4],"[11, 199, 4, 200, 52, 79, 2, 10, 5, 139]",[id='science_and_development_of_muscle_hypertr...,1,10,1.0,0.1,1.0,0.333333,0.5,NaN
1,Is there a way exercises get grouped based on ...,single_chunk,[18],"[181, 185, 182, 184, 31, 183, 20, 103, 77, 108]",[id='science_and_development_of_muscle_hypertr...,1,10,0.0,0.0,0.0,0.000000,0.0,NaN
2,"Does it matter what angle I do an exercise at,...",single_chunk,[12],"[12, 92, 16, 90, 64, 144, 163, 45, 64, 148]",[id='science_and_development_of_muscle_hypertr...,1,10,1.0,0.1,1.0,1.000000,1.0,NaN
3,What are the different directions my body can ...,single_chunk,[13],"[13, 70, 12, 93, 14, 127, 69, 183, 92, 7]",[id='science_and_development_of_muscle_hypertr...,1,10,1.0,0.1,1.0,1.000000,1.0,NaN
4,Does it really matter how wide I put my hands ...,single_chunk,[15],"[15, 64, 148, 199, 3, 14, 6, 105, 88, 200]",[id='science_and_development_of_muscle_hypertr...,1,10,1.0,0.1,1.0,1.000000,1.0,NaN

In [54]:
evaluator.summary()

                  Metric     Value
0            Precision@k  0.109091
1               Recall@k  0.674242
2                    MRR  0.571203
3                   nDCG  0.548918
4               Hit Rate  0.818182
5  Negative Success Rate  0.000000

In [55]:
evaluator.summary_by_type()

,Type,Count,Precision@k,Recall@k,MRR,nDCG,Hit Rate,Negative Success Rate
0,multi_chunk,17,0.158824,0.509804,0.591503,0.451948,0.882353,NaN
1,negative,10,NaN,NaN,NaN,NaN,NaN,0.0
2,single_chunk,27,0.077778,0.777778,0.558422,0.609973,0.777778,NaN

In [22]:
from abc import ABC, abstractmethod
from typing import Generic, TypeVar

T = TypeVar("T")


class BaseMetadataExtractor(ABC, Generic[T]):

    @abstractmethod
    def extract(
        self,
        query: str,
    ) -> T:
        """
        Extract metadata from a user query.
        """
        pass

In [23]:
from pydantic import BaseModel
from typing import Literal


class PrinciplesQueryFilter(BaseModel):

    topic: list[
        Literal[
            "program_design",
            "periodization",
            "progressive_overload",
            "volume",
            "frequency",
            "intensity",
            "load",
            "exercise_selection",
            "recovery",
            "fatigue",
            "warmup",
            "energy_systems",
        ]
    ] | None = None

    planner_stage: list[
        Literal[
            "goal_selection",
            "program_design",
            "exercise_selection",
            "progression",
            "recovery",
        ]
    ] | None = None

    goals: list[
        Literal[
            "hypertrophy",
            "strength",
            "fat_loss",
            "endurance",
        ]
    ] | None = None

    applies_to: list[
        Literal[
            "all",
            "hypertrophy",
            "strength",
            "fat_loss",
        ]
    ] | None = None

    knowledge_type: list[
        Literal[
            "definition",
            "principle",
            "recommendation",
            "warning",
            "protocol",
        ]
    ] | None = None


class GoalQueryFilter(BaseModel):

    muscle: list[
        Literal[
            "all",
            "chest",
            "back",
            "shoulders",
            "biceps",
            "triceps",
            "forearms",
            "quads",
            "hamstrings",
            "glutes",
            "calves",
            "abs",
        ]
    ] | None = None

    topic: list[
        Literal[
            "muscle_physiology",
            "neuromuscular_system",
            "muscle_activation",
            "biomechanics",

            "muscle_growth_mechanisms",
            "hypertrophy_programming",
            "maximal_strength",
            "force_production",
            "power_development",
            "neural_adaptation",

            "volume",
            "frequency",
            "intensity",
            "load",
            "exercise_selection",
            "exercise_order",
            "periodization",
            "recovery",
            "fatigue_management",
            "advanced_techniques",
        ]
    ] | None = None

    experience_level: Literal[
        "all",
        "beginner",
        "intermediate",
        "advanced",
    ] | None = None

    goals: list[
        Literal[
            "hypertrophy",
            "strength",
            "fat_loss",
        ]
    ] | None = None

In [24]:
from langchain_core.prompts import ChatPromptTemplate


GOAL_QUERY_FILTER_PROMPT = ChatPromptTemplate.from_messages(
    [
        (
            "system",
            """
You are an expert in exercise science.

Your task is to extract structured retrieval filters from a user's query.

The output will be used to filter a vector database before retrieval.

Guidelines:

1. Understand the semantic meaning of the query, not just the exact words.

2. Infer metadata when it is strongly implied by the user's intent.

3. Never guess. If you are not confident about a field, leave it empty.

4. Only extract metadata that is useful for retrieval.

5. Do not force every field to be populated.

6. Do not infer metadata solely from common associations.
   For example, "bench press" does not automatically imply "chest" unless the query is actually about training the chest.

7. Use "all" only when the user explicitly refers to everyone or to general recommendations.

8. Ignore conversational text that does not affect retrieval.

9. Return only the structured output.
            """,
        ),
        (
            "human",
            """
User Query:

{query}
            """,
        ),
    ]
)

In [25]:
from langchain_core.language_models import BaseChatModel


class GoalMetadataExtractor(
    BaseMetadataExtractor[GoalQueryFilter]
):

    def __init__(
        self,
        llm: BaseChatModel,
    ):
        self.chain = (
            GOAL_QUERY_FILTER_PROMPT
            | llm.with_structured_output(GoalQueryFilter)
        )

        self._cache: dict[str, GoalQueryFilter] = {}

    def extract(
        self,
        query: str,
    ) -> GoalQueryFilter:

        if query in self._cache:
            return self._cache[query]

        metadata = self.chain.invoke(
            {
                "query": query,
            }
        )

        self._cache[query] = metadata

        return metadata

In [26]:
from dotenv import load_dotenv

load_dotenv()
os.getenv("HF_HOME")
os.getenv("GOOGLE_API_KEY")
os.getenv("GROQ_API_KEY")
os.getenv("NVIDIA_API_KEY")
os.getenv("NVIDIA_API_KEY")

os.getenv("ITI_API_KEY")
print()

In [27]:
from enum import Enum

class LLMProvider(Enum):
    GEMINI = "gemini"
    GROQ = "groq"
    NVIDIA = "nvidia"
    OPENROUTER = "openrouter"
    ITI = "iti"


@dataclass(frozen=True)
class LLMConfig:
    provider: LLMProvider
    model: str
    temperature: float = 0.0

In [ ]:
from langchain_core.language_models.chat_models import BaseChatModel
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_groq import ChatGroq
from langchain_nvidia_ai_endpoints import ChatNVIDIA
from langchain_openai import ChatOpenAI

def create_llm(config: LLMConfig) -> BaseChatModel:

    if config.provider == LLMProvider.GEMINI:
        return ChatGoogleGenerativeAI(
            model=config.model,
            temperature=config.temperature,
        )

    if config.provider == LLMProvider.GROQ:
        return ChatGroq(
            model=config.model,
            temperature=config.temperature,
        )
    
    if config.provider == LLMProvider.NVIDIA:
        return ChatNVIDIA(
            model=config.model,
            temperature=config.temperature,
        )
    
    if config.provider == LLMProvider.OPENROUTER:
        return ChatOpenAI(
            openai_api_base="https://openrouter.ai/api/v1",
            model=config.model,
            api_key=os.getenv("OPENROUTER_API_KEY"),
            temperature=config.temperature,
        )
    
    if config.provider == LLMProvider.ITI:
        return ChatOpenAI(
            base_url="http://apiaccess.iti.net.eg/api/v1",
            model=config.model,
            temperature=config.temperature,
        )

    raise ValueError(
        f"Unsupported provider: {config.provider}"
    )

In [34]:

config = LLMConfig(
    provider=LLMProvider.GROQ,
    model="openai/gpt-oss-120b",
)

llm = create_llm(config)

In [29]:
T = TypeVar("T")

class BaseFilterBuilder(ABC, Generic[T]):

    @abstractmethod
    def build(
        self,
        query_filter: T,
    ):
        pass

In [30]:
from qdrant_client.models import (
    Filter,
    FieldCondition,
    MatchAny,
    MatchValue,
)


class GoalFilterBuilder(
    BaseFilterBuilder[GoalQueryFilter]
):

    def build(
        self,
        query_filter: GoalQueryFilter,
    ) -> Filter:

        must = []

        if query_filter.muscle:
            must.append(
                FieldCondition(
                    key="metadata.muscle",
                    match=MatchAny(
                        any=[
                            *query_filter.muscle,
                            "all",
                        ],
                    ),
                )
            )

        if query_filter.topic:
            must.append(
                FieldCondition(
                    key="metadata.topic",
                    match=MatchAny(
                        any=query_filter.topic,
                    ),
                )
            )

        if query_filter.experience_level:
            must.append(
                FieldCondition(
                    key="metadata.experience_level",
                    match=MatchAny(
                        any=[
                            query_filter.experience_level,
                            "all",
                        ],
                    ),
                )
            )

        if query_filter.goals:
            must.append(
                FieldCondition(
                    key="metadata.goals",
                    match=MatchAny(
                        any=query_filter.goals,
                    ),
                )
            )

        return Filter(
            must=must,
        )

In [87]:
query_filter = GoalQueryFilter(
    muscle=["chest"],
    topic=["volume", "intensity"],
    experience_level="beginner",
    goals=["hypertrophy"],
)

builder = GoalFilterBuilder()

builder.build(query_filter)

Filter(should=None, min_should=None, must=[FieldCondition(key='metadata.muscle', match=MatchAny(any=['chest', 'all']), range=None, geo_bounding_box=None, geo_radius=None, geo_polygon=None, values_count=None, is_empty=None, is_null=None), FieldCondition(key='metadata.topic', match=MatchAny(any=['volume', 'intensity']), range=None, geo_bounding_box=None, geo_radius=None, geo_polygon=None, values_count=None, is_empty=None, is_null=None), FieldCondition(key='metadata.experience_level', match=MatchAny(any=['beginner', 'all']), range=None, geo_bounding_box=None, geo_radius=None, geo_polygon=None, values_count=None, is_empty=None, is_null=None), FieldCondition(key='metadata.goals', match=MatchAny(any=['hypertrophy']), range=None, geo_bounding_box=None, geo_radius=None, geo_polygon=None, values_count=None, is_empty=None, is_null=None)], must_not=None)

In [31]:
class FilteredHybridRetriever(BaseRetriever):

    def __init__(
        self,
        retriever: HybridRetriever,
        metadata_extractor: GoalMetadataExtractor,
        filter_builder: GoalFilterBuilder,
    ):
        self.retriever = retriever
        self.metadata_extractor = metadata_extractor
        self.filter_builder = filter_builder

    def retrieve(
        self,
        query: str,
    ) -> list[ScoredChunk]:

        query_filter = self.metadata_extractor.extract(query)

        qdrant_filter = self.filter_builder.build(query_filter)

        return self.retriever.retrieve(
            query=query,
            query_filter=qdrant_filter,
        )

In [93]:
hybrid_retriever = HybridRetriever(
    client=qdrant,
    collection_name="hypertrophy",
    dense_model=dense_model,
    sparse_model=bm25,
)

metadata_extractor = GoalMetadataExtractor(
    llm=llm,
)

filter_builder = GoalFilterBuilder()

filtered_retriever = FilteredHybridRetriever(
    retriever=hybrid_retriever,
    metadata_extractor=metadata_extractor,
    filter_builder=filter_builder,
)

In [90]:
results = filtered_retriever.retrieve(
    "How many sets should beginners perform for chest hypertrophy?"
)

len(results)

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

10

In [91]:
query_filter = metadata_extractor.extract(
    "How many sets should beginners perform for chest hypertrophy?"
)

print(query_filter)

print(filter_builder.build(query_filter))

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

muscle=['chest'] topic=['volume'] experience_level='beginner' goals=['hypertrophy']
should=None min_should=None must=[FieldCondition(key='metadata.muscle', match=MatchAny(any=['chest', 'all']), range=None, geo_bounding_box=None, geo_radius=None, geo_polygon=None, values_count=None, is_empty=None, is_null=None), FieldCondition(key='metadata.topic', match=MatchAny(any=['volume']), range=None, geo_bounding_box=None, geo_radius=None, geo_polygon=None, values_count=None, is_empty=None, is_null=None), FieldCondition(key='metadata.experience_level', match=MatchAny(any=['beginner', 'all']), range=None, geo_bounding_box=None, geo_radius=None, geo_polygon=None, values_count=None, is_empty=None, is_null=None), FieldCondition(key='metadata.goals', match=MatchAny(any=['hypertrophy']), range=None, geo_bounding_box=None, geo_radius=None, geo_polygon=None, values_count=None, is_empty=None, is_null=None)] must_not=None

In [92]:
results = filtered_retriever.retrieve(
    "How many sets should beginners perform for chest hypertrophy?"
)

results[0]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

ScoredChunk(id='science_and_development_of_muscle_hypertrophy_000675', text='- Multiset protocols favoring higher volumes of resistance training optimize the hypertrophic response. A range of 10 to 20 sets per muscle is a general guideline for weekly volume prescription. That said, there is a fairly wide interindividual response to the volume dose, and thus some people will thrive on somewhat lower volumes, while others will benefit from slightly higher volumes. Strategic use of very high volumes (~30+ sets per muscle) can be employed to help bring up lagging muscle groups. To avoid overtraining, overall volume should be progressively increased over the course of a training cycle; periods of reduced training volume should be integrated regularly to facilitate the recovery process.', book='Science and Development of Muscle Hypertrophy', chapter='Chapter 4: Role of Resistance Training Variables in Hypertrophy', collection='hypertrophy', chunk_index=223, metadata=GoalNamespaceMetadata(muscle=['all'], topic=['volume', 'periodization', 'recovery'], experience_level='all', goals=['hypertrophy']), score=0.5)

In [32]:


class RetrieverExperimentRunner:

    def __init__(
        self,
        evaluation_dataset: list[dict],
    ):
        self.dataset = evaluation_dataset

        self.summary_results = []
        self.type_results = []

    def run(
        self,
        name: str,
        retriever: BaseRetriever,
    ) -> None:

        evaluator = RetrieverEvaluator(
            retriever=retriever,
            evaluation_dataset=self.dataset,
        )

        evaluator.evaluate()

        summary = evaluator.summary().set_index("Metric")["Value"].to_dict()
        summary["Experiment"] = name

        self.summary_results.append(summary)

        by_type = evaluator.summary_by_type()
        by_type.insert(0, "Experiment", name)

        self.type_results.append(by_type)

    def summary(
        self,
    ) -> pd.DataFrame:

        return (
            pd.DataFrame(self.summary_results)
            .set_index("Experiment")
        )

    def summary_by_type(
        self,
    ) -> pd.DataFrame:

        return pd.concat(
            self.type_results,
            ignore_index=True,
        )

In [ ]:
runner = RetrieverExperimentRunner(
    evaluation_dataset=evaluation_dataset,
)

runner.run(
    name="Hybrid",
    retriever=hybrid_retriever,
)

runner.run(
    name="Hybrid + Metadata",
    retriever=filtered_retriever,
)

runner.summary()

In [95]:
runner.summary_by_type()

,Experiment,Type,Count,Precision@k,Recall@k,MRR,nDCG,Hit Rate,Negative Success Rate
0,Hybrid,multi_chunk,17,0.158824,0.509804,0.591503,0.451948,0.882353,NaN
1,Hybrid,negative,10,NaN,NaN,NaN,NaN,NaN,0.0
2,Hybrid,single_chunk,27,0.077778,0.777778,0.558422,0.609973,0.777778,NaN
3,Hybrid + Metadata,multi_chunk,17,0.158824,0.509804,0.591503,0.451948,0.882353,NaN
4,Hybrid + Metadata,negative,10,NaN,NaN,NaN,NaN,NaN,0.0
5,Hybrid + Metadata,single_chunk,27,0.077778,0.777778,0.558422,0.609973,0.777778,NaN

In [33]:
from abc import ABC, abstractmethod

class BaseReranker(ABC):

    @abstractmethod
    def rerank(
        self,
        query: str,
        chunks: list[ScoredChunk],
    ) -> list[ScoredChunk]:
        """
        Re-rank retrieved chunks according to their relevance to the query.
        """
        ...

In [34]:

class CrossEncoderReranker(BaseReranker):

    def __init__(
        self,
        model_name: str,
        device: str | None = None,
        batch_size: int = 16,
    ):
        self.batch_size = batch_size
        self.model = CrossEncoder(
            model_name,
            device=device,
        )

    def rerank(
        self,
        query: str,
        chunks: list[ScoredChunk],
    ) -> list[ScoredChunk]:

        pairs = [
            (query, chunk.text)
            for chunk in chunks
        ]

        scores = self.model.predict(
            pairs,
            batch_size=self.batch_size,
        )

        reranked_chunks = [
            chunk.model_copy(
                update={"score": float(score)}
            )
            for chunk, score in zip(chunks, scores)
        ]

        return sorted(
            reranked_chunks,
            key=lambda chunk: chunk.score,
            reverse=True,
        )

In [35]:
class RerankingRetriever(BaseRetriever):

    def __init__(
        self,
        retriever: BaseRetriever,
        reranker: BaseReranker,
    ):
        self.retriever = retriever
        self.reranker = reranker

    def retrieve(
        self,
        query: str,
    ) -> list[ScoredChunk]:

        chunks = self.retriever.retrieve(query=query)

        return self.reranker.rerank(
            query=query,
            chunks=chunks,
        )

In [ ]:
hybrid_retriever = HybridRetriever(
    client=qdrant,
    collection_name="hypertrophy",
    dense_model=dense_model,
    sparse_model=bm25,
    top_k=50
)

In [ ]:
reranker = CrossEncoderReranker(
    model_name="assets/models/bge-reranker-v2-m3",
    device="cpu",
)

reranker_hybrid_retriever = RerankingRetriever(
    retriever=hybrid_retriever,  
    reranker=reranker,
)

In [ ]:
results = reranker_hybrid_retriever.retrieve(
    query="best exercises for chest hypertrophy",
)

In [119]:
print(len(results))

50

In [120]:
for chunk in results[:5]:
    print(chunk.score)

0.9473987817764282
0.7512507438659668
0.4921760857105255
0.4690931439399719
0.42785853147506714

In [ ]:
hybrid_results = hybrid_retriever.retrieve(
    query="best exercises for chest hypertrophy",
)

reranked_results = reranker_hybrid_retriever.retrieve(
    query="best exercises for chest hypertrophy",
)

In [122]:
for i in range(10):
    print(
        i + 1,
        hybrid_results[i].score,
        " | ",
        reranked_results[i].score,
        " | ",
        reranked_results[i].text[:80],
    )

1 0.6  |  0.9473987817764282  |  ## Chest

The pectoralis major is maximally activated in the transverse plane us
2 0.5833333333333334  |  0.7512507438659668  |  1. Long-length accentuated force exercises create maximal torque while the prime
3 0.38095238095238093  |  0.4921760857105255  |  ## KEY POINT

Maximal hypertrophy can be best achieved by systematically varying
4 0.3787878787878788  |  0.4690931439399719  |  - Once competency in the basic movement patterns has been established, a variety
5 0.29  |  0.42785853147506714  |  Exercise selection is another factor worthy of consideration when determining re
6 0.26666666666666666  |  0.4120422303676605  |  ## KEY POINT

Once trainees have learned the movement patterns of basic resistan
7 0.25396825396825395  |  0.3975623548030853  |  Taking the body of literature on the topic into account, interference appears to
8 0.25  |  0.32435476779937744  |  The impact of volume may be at least in part frequency dependent. Schwartz and c
9 0.23846153846153847  |  0.30963537096977234  |  Several studies have attempted to directly quantify the effects of exercise orde
10 0.175  |  0.2890844941139221  |  3 weekly sessions appears to be warranted. Very high training frequencies (6 day

In [123]:
for i in range(10):
    print("=" * 80)
    print("Hybrid:")
    print(hybrid_results[i].text[:100])

    print("\nReranked:")
    print(reranked_results[i].text[:100])

================================================================================
Hybrid:
## KEY POINT

Maximal hypertrophy can be best achieved by systematically varying the exercises perfo

Reranked:
## Chest

The pectoralis major is maximally activated in the transverse plane using horizontal adduc
================================================================================
Hybrid:
## Chest

The pectoralis major is maximally activated in the transverse plane using horizontal adduc

Reranked:
1. Long-length accentuated force exercises create maximal torque while the prime movers are stretche
================================================================================
Hybrid:
It should be noted that that per-session training time in the strength group was 70 minutes, whereas

Reranked:
## KEY POINT

Maximal hypertrophy can be best achieved by systematically varying the exercises perfo
================================================================================
Hybrid:
- Once competency in the basic movement patterns has been established, a variety of exercises should

Reranked:
- Once competency in the basic movement patterns has been established, a variety of exercises should
================================================================================
Hybrid:
Exercise selection is another factor worthy of consideration when determining rest intervals for hyp

Reranked:
Exercise selection is another factor worthy of consideration when determining rest intervals for hyp
================================================================================
Hybrid:
## KEY POINT

Once trainees have learned the movement patterns of basic resistance training exercise

Reranked:
## KEY POINT

Once trainees have learned the movement patterns of basic resistance training exercise
================================================================================
Hybrid:
Hypertrophy-oriented routines generally involve a high volume of work per muscle group in a session

Reranked:
Taking the body of literature on the topic into account, interference appears to be best minimized b
================================================================================
Hybrid:
# Chapter 6: Role of Aerobic Training in Hypertrophy

Reranked:
The impact of volume may be at least in part frequency dependent. Schwartz and colleagues

## KEY PO
================================================================================
Hybrid:
1. Long-length accentuated force exercises create maximal torque while the prime movers are stretche

Reranked:
Several studies have attempted to directly quantify the effects of exercise order on muscle hypertro
================================================================================
Hybrid:
Taking the body of literature on the topic into account, interference appears to be best minimized b

Reranked:
3 weekly sessions appears to be warranted. Very high training frequencies (6 days per week) do not a

In [42]:
# config = LLMConfig(
#     provider=LLMProvider.NVIDIA,
#     model="nvidia/nemotron-3-super-120b-a12b",
# )

config = LLMConfig(
    provider=LLMProvider.GROQ,
    model="openai/gpt-oss-120b",
)

# config = LLMConfig(
#    provider=LLMProvider.GEMINI,
#    model="models/gemini-2.5-flash"
# )

# config = LLMConfig(
#     provider=LLMProvider.OPENROUTER,
#     model="nvidia/nemotron-3-ultra-550b-a55b:free",
#     temperature=0
# )

# config = LLMConfig(
#     provider=LLMProvider.ITI,
#     model="anthropic.claude-sonnet-4-6",
#     temperature=0
# )

llm = create_llm(config)

In [43]:

hybrid_retriever = HybridRetriever(
    client=qdrant,
    collection_name="hypertrophy",
    dense_model=dense_model,
    sparse_model=bm25,
    top_k=50
)

metadata_extractor = GoalMetadataExtractor(
    llm=llm,
)

filter_builder = GoalFilterBuilder()

filtered_retriever = FilteredHybridRetriever(
    retriever=hybrid_retriever,
    metadata_extractor=metadata_extractor,
    filter_builder=filter_builder,
)

reranker_hybrid_filtered_retriever = RerankingRetriever(
    retriever=filtered_retriever,  
    reranker=reranker,
)

In [128]:
runner = RetrieverExperimentRunner(
    evaluation_dataset=evaluation_dataset,
)

runner.run(
    name="Hybrid",
    retriever=hybrid_retriever,
)

runner.run(
    name="Hybrid + Metadata",
    retriever=filtered_retriever,
)

runner.run(
    name="Hybrid + Reranker",
    retriever=reranker_hybrid_retriever
)

runner.run(
    name=" Metadata + Hybrid + Reranker",
    retriever=reranker_hybrid_filtered_retriever
    
)

runner.summary()

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
INFO:groq._base_client:Retrying request to /openai/v1/chat/completions in 6.000000 seconds
INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
INFO:groq._base_client:Retrying request to /openai/v1/chat/completions in 4.000000 seconds
INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
INFO:groq._base_client:Retrying request to /openai/v1/chat/completions in 6.000000 seconds
INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
INFO:groq._base_client:Retrying request to /openai/v1/chat/completions in 6.000000 seconds
INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
INFO:groq._base_client:Retrying request to /openai/v1/chat/completions in 6.000000 seconds
INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
INFO:groq._base_client:Retrying request to /openai/v1/chat/completions in 4.000000 seconds
INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
INFO:groq._base_client:Retrying request to /openai/v1/chat/completions in 4.000000 seconds
INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
INFO:groq._base_client:Retrying request to /openai/v1/chat/completions in 5.000000 seconds
INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
INFO:groq._base_client:Retrying request to /openai/v1/chat/completions in 1.000000 seconds
INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
INFO:groq._base_client:Retrying request to /openai/v1/chat/completions in 6.000000 seconds
INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
INFO:groq._base_client:Retrying request to /openai/v1/chat/completions in 6.000000 seconds
INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
INFO:groq._base_client:Retrying request to /openai/v1/chat/completions in 1.000000 seconds
INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
INFO:groq._base_client:Retrying request to /openai/v1/chat/completions in 6.000000 seconds
INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
INFO:groq._base_client:Retrying request to /openai/v1/chat/completions in 5.000000 seconds
INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
INFO:groq._base_client:Retrying request to /openai/v1/chat/completions in 1.000000 seconds
INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
INFO:groq._base_client:Retrying request to /openai/v1/chat/completions in 1.000000 seconds
INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
INFO:groq._base_client:Retrying request to /openai/v1/chat/completions in 2.000000 seconds
INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
INFO:groq._base_client:Retrying request to /openai/v1/chat/completions in 5.000000 seconds
INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
INFO:groq._base_client:Retrying request to /openai/v1/chat/completions in 1.000000 seconds
INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
INFO:groq._base_client:Retrying request to /openai/v1/chat/completions in 1.000000 seconds
INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
INFO:groq._base_client:Retrying request to /openai/v1/chat/completions in 6.000000 seconds
INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
INFO:groq._base_client:Retrying request to /openai/v1/chat/completions in 5.000000 seconds
INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
INFO:groq._base_client:Retrying request to /openai/v1/chat/completions in 3.000000 seconds
INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
INFO:groq._base_client:Retrying request to /openai/v1/chat/completions in 2.000000 seconds
INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
INFO:groq._base_client:Retrying request to /openai/v1/chat/completions in 2.000000 seconds
INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
INFO:groq._base_client:Retrying request to /openai/v1/chat/completions in 1.000000 seconds
INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
INFO:groq._base_client:Retrying request to /openai/v1/chat/completions in 2.000000 seconds
INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
INFO:groq._base_client:Retrying request to /openai/v1/chat/completions in 4.000000 seconds
INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
INFO:groq._base_client:Retrying request to /openai/v1/chat/completions in 6.000000 seconds
INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
INFO:groq._base_client:Retrying request to /openai/v1/chat/completions in 5.000000 seconds
INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
INFO:groq._base_client:Retrying request to /openai/v1/chat/completions in 1.000000 seconds
INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
INFO:groq._base_client:Retrying request to /openai/v1/chat/completions in 6.000000 seconds
INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

,Precision@k,Recall@k,MRR,nDCG,Hit Rate,Negative Success Rate
Experiment,,,,,,
Hybrid,0.029545,0.886364,0.580508,0.638371,0.977273,0.0
Hybrid + Metadata,0.029545,0.886364,0.580508,0.638371,0.977273,0.0
Hybrid + Reranker,0.029545,0.886364,0.647340,0.694599,0.977273,0.0
Metadata + Hybrid + Reranker,0.029545,0.886364,0.647340,0.694599,0.977273,0.0

In [129]:
runner.summary_by_type()

,Experiment,Type,Count,Precision@k,Recall@k,MRR,nDCG,Hit Rate,Negative Success Rate
0,Hybrid,multi_chunk,17,0.045882,0.764706,0.589836,0.570509,1.000000,NaN
1,Hybrid,negative,10,NaN,NaN,NaN,NaN,NaN,0.0
2,Hybrid,single_chunk,27,0.019259,0.962963,0.574635,0.681099,0.962963,NaN
3,Hybrid + Metadata,multi_chunk,17,0.045882,0.764706,0.589836,0.570509,1.000000,NaN
4,Hybrid + Metadata,negative,10,NaN,NaN,NaN,NaN,NaN,0.0
5,Hybrid + Metadata,single_chunk,27,0.019259,0.962963,0.574635,0.681099,0.962963,NaN
6,Hybrid + Reranker,multi_chunk,17,0.045882,0.764706,0.603270,0.582211,1.000000,NaN
7,Hybrid + Reranker,negative,10,NaN,NaN,NaN,NaN,NaN,0.0
8,Hybrid + Reranker,single_chunk,27,0.019259,0.962963,0.675087,0.765362,0.962963,NaN
9,Metadata + Hybrid + Reranker,multi_chunk,17,0.045882,0.764706,0.603270,0.582211,1.000000,NaN
10,Metadata + Hybrid + Reranker,negative,10,NaN,NaN,NaN,NaN,NaN,0.0
11,Metadata + Hybrid + Reranker,single_chunk,27,0.019259,0.962963,0.675087,0.765362,0.962963,NaN

In [44]:
class RAGResponse(BaseModel):
    answer: str
    chunks: list[ScoredChunk]

In [45]:

class BaseRAG(ABC):

    @abstractmethod
    def invoke(
        self,
        query: str,
    ) -> RAGResponse:
        ...

In [46]:
from langchain_core.language_models import BaseChatModel
from langchain_core.prompts import ChatPromptTemplate


class RAG(BaseRAG):

    def __init__(
        self,
        retriever: BaseRetriever,
        llm: BaseChatModel,
        prompt: ChatPromptTemplate,
        context_top_k: int = 10,
    ):
        self.retriever = retriever
        self.context_top_k = context_top_k
        self.chain = prompt | llm

    def _build_context(
        self,
        chunks: list[ScoredChunk],
    ) -> str:

        return "\n\n".join(
            chunk.text
            for chunk in chunks
        )

    def invoke(
        self,
        query: str,
    ) -> RAGResponse:

        chunks = self.retriever.retrieve(
            query=query,
        )

        selected_chunks = chunks[: self.context_top_k]

        context = self._build_context(selected_chunks)

        response = self.chain.invoke(
            {
                "query": query,
                "context": context,
            }
        )

        return RAGResponse(
            answer=response.content,
            chunks=selected_chunks,
        )

In [47]:
RAG_PROMPT = ChatPromptTemplate.from_messages(
    [
        (
            "system",
            """
You are an expert in exercise science.

Answer ONLY using the provided context.

If the context does not contain the answer, say you don't know.

Do not invent information.

Context:
{context}
""",
        ),
        (
            "human",
            "{query}",
        ),
    ]
)

In [50]:
rag = RAG(
    retriever=reranker_hybrid_filtered_retriever,
    llm=llm,
    prompt=RAG_PROMPT,
    context_top_k=5,
)

response = rag.invoke(
    "What is the optimal training volume for hypertrophy?"
)

print(response.answer)

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

The literature suggests that, as a general guideline, **about 10 to 20 sets per muscle group each week** is optimal for maximizing hypertrophy. More advanced lifters may benefit from the higher end of that range, and occasional very‑high volumes (≈30 + sets) can be used strategically for lagging muscles, but the 10‑20‑set per‑week range is the recommended baseline.

In [51]:
response = rag.invoke(
    "How do I cook pasta?"
)

print(response.answer)

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

I don't know.

In [52]:
evaluation_dataset[0]

{'question': "Why can a muscle actually get stronger when it's stretched a bit past its normal resting length instead of weaker?",
 'relevant_chunks': [4],
 'type': 'single_chunk'}

In [53]:
response = rag.invoke(evaluation_dataset[0]["question"])
response

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

RAGResponse(answer='The muscle’s ability to generate force depends on how the actin and myosin filaments line up inside each sarcomere.\u202fAt the muscle’s normal resting length the overlap of those filaments is already good, so force production is near its peak.\u202fWhen the muscle is stretched a little beyond that resting length (about\u202f125\u202f%–140\u202f% of resting length), the sarcomeres are lengthened just enough that the filaments are pulled closer together again and the sensitivity of the contractile apparatus to calcium rises.\u202fThis “enhanced calcium sensitivity” and the slightly improved geometry increase the chance that cross‑bridges will form, allowing the muscle to produce even more force than at true resting length.\n\nBecause the muscle can generate higher forces when it is trained in that stretched position, the mechanical stress and time‑under‑tension are greater.\u202fThose larger mechanical stimuli trigger stronger anabolic signaling (e.g., higher IGF‑1 levels) and lead to greater hypertrophic adaptations—larger cross‑sectional area, longer fascicles, and even increases in fiber number.\u202fThus, training a muscle at a modestly lengthened position can make it stronger, not weaker, by improving cross‑bridge formation and stimulating more robust growth pathways.', chunks=[ScoredChunk(id='science_and_development_of_muscle_hypertrophy_000695', text='showed post-exercise increases in muscle thickness favored the group that performed loaded stretch training compared to passive rest (23% vs. 9%, respectively). The underlying mechanisms of these findings are unclear but may be related to a greater time under tension, essentially corresponding to a higher volume or perhaps higher mechanical tension achieved by extended loading at long muscle lengths. However, it should be noted that these data have not been published in a peer-reviewed journal and thus must be interpreted with circumspection.\n\n## KEY POINT', book='Science and Development of Muscle Hypertrophy', chapter='Chapter 5: Advanced Training Practices', collection='hypertrophy', chunk_index=11, metadata=GoalNamespaceMetadata(muscle=['all'], topic=['muscle_growth_mechanisms', 'volume', 'load'], experience_level='advanced', goals=['hypertrophy']), score=0.30837154388427734), ScoredChunk(id='science_and_development_of_muscle_hypertrophy_000937', text='The capacity of a muscle fiber to produce force is predicated on the position of the actin and myosin filaments in its sarcomeres. This phenomenon, known as the length-tension relationship (), can be harnessed to target muscles or portions of them by making them more or less active during exercise. Optimal force-producing capacity is often said to take place at approximately resting length, whereby the overlap of actin and myosin filaments is maximized, thus facilitating optimal crossbridge formation. However, working a muscle at 125% to 140% of resting length may confer even greater benefits on force output because the stretching of sarcomeres brings the myofilaments together and enhances calcium sensitivity; it is hypothesized that the greater potential for crossbridge attachment from', book='Science and Development of Muscle Hypertrophy', chapter='Chapter 8: Program Design for Maximal Hypertrophy', collection='hypertrophy', chunk_index=4, metadata=GoalNamespaceMetadata(muscle=['all'], topic=['muscle_physiology', 'force_production'], experience_level='all', goals=['strength']), score=0.2594485282897949), ScoredChunk(id='science_and_development_of_muscle_hypertrophy_000651', text='Evidence suggests that training at longer muscle lengths (i.e., when the muscle is in a stretched position) promotes greater hypertrophic adaptations than training at shorter muscle lengths. McMahon and colleagues (150) compared the hypertrophic response to knee extensions at shortened (0° to 50° of knee flexion) or lengthened (40° to 90° of knee flexion) positions. Results showed significantly greater increases in distal cross-sectional area of the quadriceps (53% vs. 18%) as well as fascicle length (29% vs. 14%) in favor of the long- versus short-length training, respectively. Moreover, IGF-1 levels were significantly greater following longlength training than following short-length training (31% vs. 7%, respectively), suggesting that exercise at long muscle lengths induces greater', book='Science and Development of Muscle Hypertrophy', chapter='Chapter 4: Role of Resistance Training Variables in Hypertrophy', collection='hypertrophy', chunk_index=199, metadata=GoalNamespaceMetadata(muscle=['quads'], topic=['muscle_growth_mechanisms', 'muscle_physiology'], experience_level='all', goals=['hypertrophy']), score=0.24059292674064636), ScoredChunk(id='science_and_development_of_muscle_hypertrophy_000686', text='## Loaded Stretch Training\n\nStretch training is commonly prescribed for improving measures of mobility and flexibility. However, evidence indicates that forms of stretch training may in fact mediate anabolic adaptations. For instance, research shows a hypertrophic benefit to dynamic training at long muscle lengths (i.e., stretched position) compared to training in a shortened position (52, 53). The mechanistic reasons for these findings remain unknown, but possibilities include heightened ultrastructural disruption, greater mechanical stress, or perhaps a combination of the two phenomena. Regardless of the mechanisms, a logical rationale exists for integrating stretch training into a resistance training program to confer an additive effect on muscle growth.', book='Science and Development of Muscle Hypertrophy', chapter='Chapter 5: Advanced Training Practices', collection='hypertrophy', chunk_index=2, metadata=GoalNamespaceMetadata(muscle=['all'], topic=['hypertrophy_programming'], experience_level='all', goals=['hypertrophy']), score=0.11661938577890396), ScoredChunk(id='science_and_development_of_muscle_hypertrophy_000689', text="The intensity of stretch training can be heightened by the addition of a load. The use of loaded stretch for promoting hypertrophy has sound research-based support in animal models. Seminal studies from the lab of William Gonyea demonstrated that the application of a load to the stretched wings of Japanese quails produced rapid and marked increases in muscle mass. In one study, the birds' wings were chronically elevated and loaded with a weight corresponding to 10% of body mass, thereby placing the anterior latissimus dorsi muscle under persistent stretch (2). After 30 days of consistent loaded stretch, muscle cross-sectional area increased 57% and fiber number increased 52%, indicating that both hypertrophy- and hyperplasia-mediated changes had taken place. A follow-up study (5)", book='Science and Development of Muscle Hypertrophy', chapter='Chapter 5: Advanced Training Practices', collection='hypertrophy', chunk_index=5, metadata=GoalNamespaceMetadata(muscle=['all'], topic=['advanced_techniques'], experience_level='all', goals=['hypertrophy']), score=0.08633376657962799)])

In [54]:
ragas_sample = {
    "user_input": evaluation_dataset[0]["question"],
    "response": response.answer,
    "retrieved_contexts": [
        chunk.text for chunk in response.chunks
    ]
}

ragas_sample

{'user_input': "Why can a muscle actually get stronger when it's stretched a bit past its normal resting length instead of weaker?",
 'response': 'The muscle’s ability to generate force depends on how the actin and myosin filaments line up inside each sarcomere.\u202fAt the muscle’s normal resting length the overlap of those filaments is already good, so force production is near its peak.\u202fWhen the muscle is stretched a little beyond that resting length (about\u202f125\u202f%–140\u202f% of resting length), the sarcomeres are lengthened just enough that the filaments are pulled closer together again and the sensitivity of the contractile apparatus to calcium rises.\u202fThis “enhanced calcium sensitivity” and the slightly improved geometry increase the chance that cross‑bridges will form, allowing the muscle to produce even more force than at true resting length.\n\nBecause the muscle can generate higher forces when it is trained in that stretched position, the mechanical stress and time‑under‑tension are greater.\u202fThose larger mechanical stimuli trigger stronger anabolic signaling (e.g., higher IGF‑1 levels) and lead to greater hypertrophic adaptations—larger cross‑sectional area, longer fascicles, and even increases in fiber number.\u202fThus, training a muscle at a modestly lengthened position can make it stronger, not weaker, by improving cross‑bridge formation and stimulating more robust growth pathways.',
 'retrieved_contexts': ['showed post-exercise increases in muscle thickness favored the group that performed loaded stretch training compared to passive rest (23% vs. 9%, respectively). The underlying mechanisms of these findings are unclear but may be related to a greater time under tension, essentially corresponding to a higher volume or perhaps higher mechanical tension achieved by extended loading at long muscle lengths. However, it should be noted that these data have not been published in a peer-reviewed journal and thus must be interpreted with circumspection.\n\n## KEY POINT',
  'The capacity of a muscle fiber to produce force is predicated on the position of the actin and myosin filaments in its sarcomeres. This phenomenon, known as the length-tension relationship (), can be harnessed to target muscles or portions of them by making them more or less active during exercise. Optimal force-producing capacity is often said to take place at approximately resting length, whereby the overlap of actin and myosin filaments is maximized, thus facilitating optimal crossbridge formation. However, working a muscle at 125% to 140% of resting length may confer even greater benefits on force output because the stretching of sarcomeres brings the myofilaments together and enhances calcium sensitivity; it is hypothesized that the greater potential for crossbridge attachment from',
  'Evidence suggests that training at longer muscle lengths (i.e., when the muscle is in a stretched position) promotes greater hypertrophic adaptations than training at shorter muscle lengths. McMahon and colleagues (150) compared the hypertrophic response to knee extensions at shortened (0° to 50° of knee flexion) or lengthened (40° to 90° of knee flexion) positions. Results showed significantly greater increases in distal cross-sectional area of the quadriceps (53% vs. 18%) as well as fascicle length (29% vs. 14%) in favor of the long- versus short-length training, respectively. Moreover, IGF-1 levels were significantly greater following longlength training than following short-length training (31% vs. 7%, respectively), suggesting that exercise at long muscle lengths induces greater',
  '## Loaded Stretch Training\n\nStretch training is commonly prescribed for improving measures of mobility and flexibility. However, evidence indicates that forms of stretch training may in fact mediate anabolic adaptations. For instance, research shows a hypertrophic benefit to dynamic training at long muscle lengths (i.e., stretched position) compared to training in a shortened position (52, 53). The mechanistic reasons for these findings remain unknown, but possibilities include heightened ultrastructural disruption, greater mechanical stress, or perhaps a combination of the two phenomena. Regardless of the mechanisms, a logical rationale exists for integrating stretch training into a resistance training program to confer an additive effect on muscle growth.',
  "The intensity of stretch training can be heightened by the addition of a load. The use of loaded stretch for promoting hypertrophy has sound research-based support in animal models. Seminal studies from the lab of William Gonyea demonstrated that the application of a load to the stretched wings of Japanese quails produced rapid and marked increases in muscle mass. In one study, the birds' wings were chronically elevated and loaded with a weight corresponding to 10% of body mass, thereby placing the anterior latissimus dorsi muscle under persistent stretch (2). After 30 days of consistent loaded stretch, muscle cross-sectional area increased 57% and fiber number increased 52%, indicating that both hypertrophy- and hyperplasia-mediated changes had taken place. A follow-up study (5)"]}

In [55]:
from ragas.metrics import (
    Faithfulness,
    AnswerRelevancy,
)
from langchain_community.embeddings import HuggingFaceEmbeddings

/tmp/ipykernel_372159/1769669787.py:1: DeprecationWarning: Importing Faithfulness from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import Faithfulness
  from ragas.metrics import (
/tmp/ipykernel_372159/1769669787.py:1: DeprecationWarning: Importing AnswerRelevancy from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import AnswerRelevancy
  from ragas.metrics import (

In [56]:
type(llm)

langchain_groq.chat_models.ChatGroq

In [57]:
from ragas import evaluate
import inspect

print(inspect.signature(evaluate))

(dataset: 't.Union[Dataset, EvaluationDataset]', metrics: 't.Optional[t.Sequence[Metric]]' = None, llm: 't.Optional[BaseRagasLLM | LangchainLLM]' = None, embeddings: 't.Optional[BaseRagasEmbeddings | BaseRagasEmbedding | LangchainEmbeddings]' = None, experiment_name: 't.Optional[str]' = None, callbacks: 'Callbacks' = None, run_config: 't.Optional[RunConfig]' = None, token_usage_parser: 't.Optional[TokenUsageParser]' = None, raise_exceptions: 'bool' = False, column_map: 't.Optional[t.Dict[str, str]]' = None, show_progress: 'bool' = True, batch_size: 't.Optional[int]' = None, _run_id: 't.Optional[UUID]' = None, _pbar: 't.Optional[tqdm]' = None, return_executor: 'bool' = False, allow_nest_asyncio: 'bool' = True) -> 't.Union[EvaluationResult, Executor]'

In [58]:
from datasets import Dataset

ragas_dataset = Dataset.from_list([ragas_sample])

ragas_dataset

Dataset({
    features: ['user_input', 'response', 'retrieved_contexts'],
    num_rows: 1
})

In [85]:
from ragas.embeddings.base import BaseRagasEmbeddings

class SentenceTransformerRagasEmbeddings(BaseRagasEmbeddings):

    def __init__(self, model, model_name):
        self.client = model
        self.model = model_name

    def embed_query(self, text):
        return self.client.encode(
            text,
            convert_to_numpy=True
        ).tolist()

    def embed_documents(self, texts):
        return self.client.encode(
            texts,
            convert_to_numpy=True
        ).tolist()

    async def aembed_query(self, text):
        return self.embed_query(text)

    async def aembed_documents(self, texts):
        return self.embed_documents(texts)
    

dense_model = SentenceTransformer(
    "assets/models/bge-m3",
    device="cpu"
)

ragas_embeddings = SentenceTransformerRagasEmbeddings(
    dense_model,
    "bge-m3"
)

INFO:sentence_transformers.base.model:Loading SentenceTransformer model from assets/models/bge-m3.
The tokenizer you are loading from 'assets/models/bge-m3' with an incorrect regex pattern: https://huggingface.co/mistralai/Mistral-Small-3.1-24B-Instruct-2503/discussions/84#69121093e8b480e709447d5e. This will lead to incorrect tokenization. You should set the `fix_mistral_regex=True` flag when loading this tokenizer to fix this issue.

In [86]:
del llm

In [87]:
# config = LLMConfig(
#     provider=LLMProvider.NVIDIA,
#     model="nvidia/nemotron-3-super-120b-a12b",
# )

config = LLMConfig(
    provider=LLMProvider.GROQ,
    model="openai/gpt-oss-120b",
)

# config = LLMConfig(
#    provider=LLMProvider.GEMINI,
#    model="models/gemini-2.5-flash"
# )

# config = LLMConfig(
#     provider=LLMProvider.OPENROUTER,
#     model="nvidia/nemotron-3-ultra-550b-a55b:free",
#     temperature=0
# )

# config = LLMConfig(
#     provider=LLMProvider.ITI,
#     model="anthropic.claude-sonnet-4-6",
#     temperature=0
# )

llm = create_llm(config)

In [76]:
type(llm)

langchain_groq.chat_models.ChatGroq

In [77]:
metrics = [
    Faithfulness(),
    # AnswerRelevancy(),
]

result = evaluate(
    dataset=ragas_dataset,
    metrics=metrics,
    llm=llm,
    embeddings=ragas_embeddings,
    batch_size=1,
)

Evaluating:   0%|          | 0/1 [00:00<?, ?it/s]

Batch 1/1:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

In [78]:
result

{'faithfulness': 1.0000}

In [79]:
from ragas.metrics import AnswerRelevancy

answer_relevancy = AnswerRelevancy(
    llm=llm,
    embeddings=ragas_embeddings,
    strictness=1
)

result = evaluate(
    dataset=ragas_dataset,
    metrics=[answer_relevancy],
    llm=llm,
    embeddings=ragas_embeddings,
    raise_exceptions=True,
)

/tmp/ipykernel_372159/216054670.py:1: DeprecationWarning: Importing AnswerRelevancy from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import AnswerRelevancy
  from ragas.metrics import AnswerRelevancy

Evaluating:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

In [80]:
result

{'answer_relevancy': 0.8598}

In [81]:
ragas_samples = []

for item in evaluation_dataset:
    question = item["question"]

    rag_response = rag.invoke(question)

    ragas_samples.append(
        {
            "user_input": question,
            "response": rag_response.answer,
            "retrieved_contexts": [
                chunk.text for chunk in rag_response.chunks
            ],
        }
    )

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

In [82]:
ragas_dataset = Dataset.from_list(ragas_samples)

ragas_dataset

Dataset({
    features: ['user_input', 'response', 'retrieved_contexts'],
    num_rows: 54
})

In [89]:
ragas_dataset.to_json("ragas_dataset.json")

Creating json from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

244370

In [90]:
ragas_dataset.save_to_disk("ragas_dataset")

Saving the dataset (0/1 shards):   0%|          | 0/54 [00:00<?, ? examples/s]

In [88]:
metrics = [
    Faithfulness(),
    AnswerRelevancy(
        strictness=1
    ),
]

result = evaluate(
    dataset=ragas_dataset,
    metrics=metrics,
    llm=llm,
    embeddings=ragas_embeddings,
    batch_size=1,
    raise_exceptions=True,
)

Evaluating:   0%|          | 0/108 [00:00<?, ?it/s]

Batch 1/108:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 429 Too Many Requests"

KeyboardInterrupt:

INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
INFO:httpx:HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 429 Too Many Requests"